### ISSUE TITLE
نمایش ساعت درست نیست

### ISSUE THREAD

**Issue by milad145** [jalaali/moment-jalaali#100]
سلام و وقت بخیر 
من کد زیر رو نوشتم

```
var moment = require('moment-jalaali')
moment().format('jYYYY/jM/jD')
var a = moment('2017-07-29T12:05:30.992Z', 'YYYY-M-D HH:mm:ss').format('jYYYY/jMM/jD HH:mm:ss Z')
console.log(a)  
```
و چیزی که نمایش میده به شکل زیره 
`1396/05/7 12:05:30 +04:30`
درصورتی که من میخوام ساعت رو درست نشون بده یعنی

`1396/05/7 16:35:30`

**Comment by alitaheri** [comment]
@milad145 `1396/05/7 16:35:30` is not correct. If you want `utc` time then it will be:
```js
moment('2017-07-29T12:05:30.992Z', 'YYYY-M-D HH:mm:ss').utc().format('jYYYY/jMM/jD HH:mm:ss Z')

// --> '1396/05/7 07:35:30 +00:00'
```
If you want to enter `utc` time and get local result then do this: 

```js
const a = moment.utc('2017-07-29T12:05:30.992Z', 'YYYY-M-D HH:mm:ss')
console.log(a.local().format('jYYYY/jMM/jD HH:mm:ss Z'))

// --> '1396/05/7 16:35:30 +04:30'
```

The behavior you've described is correct. Please read the documentation for [moment.js](https://momentjs.com/docs) too.

**Comment by milad145** [comment]
@alitaheri 
سلام و خسته نباشید آقای طاهری
سرور من خارج از ایرانه . من کد زیر رو نوشتم 

`moment('2017-07-30T11:30:07.345Z', 'YYYY-M-D HH:mm:ss').local().format('jYYYY/jMM/jDD HH:mm Z')
`

و جوابی که به من میده به شکل زیره 

> 1396/05/08 07:30 -04:00

در صورتی که جواب درست باید به شکل زیر باشه

> 1396/05/08 16:00 +04:30

**Comment by alitaheri** [comment]
@milad145 This isn't related to `moment-jalaali`. This library solely handles dates. and not times or time zones. Please consider asking on slackoverflow.com I don't have enough information to help you on this one.

**Comment by milad145** [comment]
@alitaheri
سلام آقای طاهری
مشکل از سمت سرور بود
بعد از تغییر تایم زون سرور همه چی درست شد
ممنون از شما که پیگیر سوال من بودید
