### ISSUE TITLE
jMonth returns wrong month

### ISSUE THREAD

**Issue by GHR-Arash** [jalaali/moment-jalaali#105]
```
import * as moment from 'jalali-moment';
const m=moment('1396/6/3')
m.jMonth() return 5
```
it should return 6 
or i am wrong ?

**Comment by alitaheri** [comment]
The output you're getting is correct, months in js (and moment) are stored as 0 indexed. This is working as intended. if you wish to get the current month as 1 indexed, simply add one.
However, you're not using the library correctly.

You need to specify the format in which the information is provided.

```js
import * as moment from 'jalali-moment';
const m=moment('1396/6/3', 'jYYYY/jM/jD')
m.jMonth() + 1; // -> returns 6
m.format('jYYYY/jM/jD') // -> returns '1396/6/3'
```

P.S. For future reference, Please read both `moment` and `moment-jalaali`'s documentation before submitting an issue. Thank you.

**Comment by GHR-Arash** [comment]
thank you. the month is working, but how about day I 
get 6 as day, is there any workaround for the day also?
I couldn't find any info regarding this issue on documentation.

**Comment by GHR-Arash** [comment]
Ok, sorry 
I was using the wrong function to get day
i should;d use JDate().
