### ISSUE TITLE
Imoprt months

### ISSUE THREAD

**Issue by shahramSo** [jalaali/moment-jalaali#108]
As you know Moment has 4 functions moment.months, moment. monthsShort, moment.weekdays and moment.weekdaysShort, I need to get Persian months from these functions for example : momentJalaali.months. but This function doesn't return the Persian months. is there any way to return Farsi names? I've tested it after  momentJalaali.loadPersian() but the result was same.
And second question, is there any way to convert momentJalaali to IsoString (ISO 8601)?
Thanks

**Comment by mehrdaad** [comment]
@shahramSo problem solved?

**Comment by behrang** [comment]
@shahramSo Those static methods are not added to moment-jalaali. 

About ISO question, that format only has meaning in Gregorian calendar. You can work with a moment-jalaali object, manipulate it in Jalaali and finally format it to ISO and Gregorian with `toISOString` method.
