### ISSUE TITLE
Module require question

### ISSUE THREAD

**Issue by Chronicless** [jalaali/moment-jalaali#109]
Is it possible to use 2 dialects in the same app ?
I need English language + Farsi , but as this module is a plugin and its overwrites the original days,months etc in English inside moment module and loadPersian is not working on instance of moment() , it could be called only to module itself , so is there any way to use 2 languages ?
Thanks!

**Comment by alitaheri** [comment]
@Chronicless Have a look at [this section of moment.js docs](https://momentjs.com/docs/#/i18n/instance-locale/).

I think you can have any number locales as long as you locally switch their locale. However, If what you want is to have Persian locale with English wording then I suggest copying the code from the source and make your own custom locale.

**Comment by Chronicless** [comment]
@alitaheri Thanks, yeah that exactly what i wanted. As i suggested i have to do so, i just thought maybe there was already implemented such feature or another way to do that
