### ISSUE TITLE
add Object and array parsing

### ISSUE THREAD

**Issue by pajooh** [jalaali/moment-jalaali#11]
[object](http://momentjs.com/docs/#/parsing/object/) e.g.: `moment({jYear: 1393, jMonth: 3, jDay: 5});`
[array](http://momentjs.com/docs/#/parsing/array/) e.g.: `moment.j([1393, 6, 10]);` or `jMoment([1393, 6, 10]);` or something

**Comment by alitaheri** [comment]
Doesn't seem like anyone is interested. A PR is always welcome though 😁
