### ISSUE TITLE
خطا: Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by sIiiS** [jalaali/moment-jalaali#110]
برای من هم این ارور را از ورژن 2.17.1 به بعد میده ... جلالی بعد از مومنت اصلی لود میشه و اگر ورژن رو مثلا به 2.8.1 عوض کنم، درست میشه

**Comment by alitaheri** [comment]
@sIiiS 

<div dir="rtl">
لطفا stack trace رو به اشتراک بذارید. ممنون
</div>

**Comment by sIiiS** [comment]
این خطا با ورژن 2.17.1 هست که میگیرم و بهم در کنسول کروم نشون میده

‍‍`Uncaught ReferenceError: moment is not defined
    at moment-jalaali.js:30
    at moment-jalaali.js:1220`

**Comment by sIiiS** [comment]
به نتیجه‌ای رسیدید؟

**Comment by alitaheri** [comment]
<div dir="rtl">
تنها دلیلی که به ذهن من میرسه اینه که moment قبل از moment-jalaali لود نمیشه. 

میشه بگید دقیقا چجوری دارین از این ۲ تا library استفاده میکنید؟
</div>

**Comment by sIiiS** [comment]
فایل اصلی قبل از جلالی لود میشه
اگر قرار بود لود نشه که با ورژن پایین تر کار نمیداد و همین ارور رو میداد

چیزی که من دارم می بینم اینه که در ورژن 2.17.1 چیزی به نام `var moment` وجود نداره ولی در ورژن 2.8.1 این هست
شاید هم من دارم اشتباه می کنم

**Comment by alitaheri** [comment]
@sIiiS 

<div dir="rtl">
چجوری لود میکنین؟ با تگ script یا import یا require؟
</div>

**Comment by sIiiS** [comment]
@alitaheri 
با تگ script

**Comment by alitaheri** [comment]
<div dir="rtl">
میشه تگ script هم برای moment و هم برای moment-jalaali رو copy کنید اینجا؟
</div>

**Comment by sIiiS** [comment]
به این شکل استفاده می کنم

`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="moment" src="http://www.mysite.com/moment.js"></script>
<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="moment-jalaali" src="http://www.mysite.com/moment-jalaali.js"></script>`

**Comment by alitaheri** [comment]
<div dir="rtl">
مشکل async هست. هردو را با هم همزمان load میکنه. برای همین دومی اولی را نمیبینه. 
</div>

**Comment by sIiiS** [comment]
پس چرا وقتی نسخه پایین‌تر را به همین شکل استفاده می‌کنم مشکلی نداره ولی در نسخه بالا مشکل داره؟
میشه بگید چجوری رفع میشه؟

**Comment by alitaheri** [comment]
async=""
رو پاک کن
