### ISSUE TITLE
نمایش اضافی حرف الف

### ISSUE THREAD

**Issue by javansolo** [jalaali/moment-jalaali#112]
با سلام دوست عزیز کنار تمام مرداد ها یک الف اضافه درج می شود که بنده توکد دیدم اضافه در ابتدای کلمه مرداد تایپ شده است
لطفا اصلاح شود. ممنون
به طور مثال این طوری نمایش میدهد: 
چهارشنبه, 11 امرداد 1396

**Comment by alitaheri** [comment]
Please read the documentation before opening an issue. 

https://github.com/jalaali/moment-jalaali#options
