### ISSUE TITLE
روزهای هفته

### ISSUE THREAD

**Issue by aliebrahimi2015** [jalaali/moment-jalaali#113]
با سلام
نحوه برگرداندن روزهای هفته بصورت شمسی از یک تاریخ میلادی یا یک تاریخ شمسی چگونه است؟
با تشکر
2017/10/24===>سه شنبه
1396/08/01===>دوشنبه

**Comment by alitaheri** [comment]
@aliebrahimi2015 Please keep in mind, this library **extends** the functionality of `moment.js`. Read both documentations before creating an issue here.

But for the record, you can use this utility: https://momentjs.com/docs/#/get-set/iso-weekday/

**Comment by Arshiamidos** [comment]
let  m = moment() // Parse a Jalaali date
m.format('jYYYY/jM/jD') // 13xx/xx/xx 
moment('1397/03/19').day()  //4
