### ISSUE TITLE
angular 2 datePicker

### ISSUE THREAD

**Issue by sasanazizi** [jalaali/moment-jalaali#116]
hey @behrang , i'm using a angular 2 datePicker with moment calendar in my project, and now i just want add jalali date on this component, can you help me ? 

my datePicker is : https://www.npmjs.com/package/ng2-date-picker

in the same vein : 
```
import * as moment from 'jalali-moment';
moment.loadPersian(true);
moment.locale('fa-IR');
```
but jalali calander not displayed in datePicker (e.g: مهر ، آبان), Now just week days are currect!

**Comment by behrang** [comment]
Hey @sasanazizi, this library does not change moment, it extends moment with some more methods (like jMonth). So it is not possible to change calendar system of date pickers by just importing this library. A solution is to fork date picker, and change function and method calls to use the appropriate Jalaali version.

Some other date pickers using this library are available on the project home page (react-advance-jalaali-datepicker and ng-jalali-flat-datepicker).
