### ISSUE TITLE
عدم امکان انتخاب تاریخ های قدیمی

### ISSUE THREAD

**Issue by heidarbozorg** [jalaali/moment-jalaali#124]
با سلام و تشکر از شما بابت تولید این کتابخانه
یک مشکلی که من  مشاهده کردم **عدم امکان تاریخ های قدیمی** بود. در کومبو مربوط به انتخاب سال فقط 10 سال اخیر را نمایش میدهد.
پیشنهاد میکنم در کنار کومبو سال **امکان تایپ سال** مورد نظر کاربر درون همان کومبو قرار دهید.

**Comment by behrang** [comment]
درود
این پروژه یک کتابخانه است و کومبو ندارد.
احتمالا پروژه ی درستی را انتخاب نکرده اید.
