### ISSUE TITLE
React component which uses this plugin

### ISSUE THREAD

**Issue by saeidalidadi** [jalaali/moment-jalaali#125]
This is a [component ](https://github.com/saeidalidadi/rj-calendar) that supports Jalaali system by using this component. this is such an awesome plugin for jalaali system. :+1:

**Comment by behrang** [comment]
I don't see any Jalaali picture in the Readme and I can't test it. I think it is better to change Readme a little to, so the Jalaali part is reflected a little more.

Anyway, you can change the Readme of moment-jalaali and send a pull request.

**Comment by saeidalidadi** [comment]
`Github` has not loaded the screenshot, but it is in [document page](https://saeidalidadi.github.io/rj-calendar/).

The Jalaali part is in progress and I will fix it in future commits.
Anyway thanks to your attentions.
