### ISSUE TITLE
Misbehavior in Safari

### ISSUE THREAD

**Issue by sassanh** [jalaali/moment-jalaali#128]
Running `moment(new Date(2018,2,22,0,0,0)).startOf('day').format('jYY/jMM/jDD HH:mm:ss ZZ')` in Safari returns:
```
"97/01/01 00:00:00 +0330"
```
The problem doesn't exist in Chrome:
```
"97/01/02 01:00:00 +0430"
```
nor in Firefox
```
"97/01/02 01:00:00 +0430"
```

**Comment by sassanh** [comment]
Is `moment-jalali` taking care of sunlight saving or is it done by the browser?

**Comment by sassanh** [comment]
In Firefox there's another related issue, both
```
moment(new Date(2018,2,22,0,0,0)).startOf('day').format('jDD')
```
and
```
moment(new Date(2018,2,21,0,0,0)).startOf('day').format('jDD')
```
return "01".

**Comment by sassanh** [comment]
After upgrading Firefox, I see it has no problems anymore.

**Comment by behrang** [comment]
Is it related to `moment-jalaali`? Can you test `moment` alone?

**Comment by sassanh** [comment]
Yeah seems like the problem is in `momentjs`. So I guess we should close it here, I reported it there:
https://github.com/moment/moment/issues/4469
