### ISSUE TITLE
How to change language after call loadPersian() method ?

### ISSUE THREAD

**Issue by h4mit** [jalaali/moment-jalaali#132]
Hi, I'm want to change language default moment caption before call loadPersian() method, for multi language application. please help me.
regards 🌷

**Comment by alitaheri** [comment]
@h4mit this isn't related to moment-jalaali. it's how momentjs works. I suggest you to [change the locale locally](https://momentjs.com/docs/#/i18n/instance-locale/) depending on your current language rather than globally
