### ISSUE TITLE
failed to require "moment/locale/fa"

### ISSUE THREAD

**Issue by essivision** [jalaali/moment-jalaali#137]
Hi,
I have problem with initial moment-jalaali error me:
```
Uncaught Error: failed to require "moment/locale/fa"
    at require (moment-jalaali.js:14)
    at moment-jalaali.js:322
    at require (moment-jalaali.js:18)
    at moment-jalaali.js:1224
    at moment-jalaali.js:1226
``` 

What should I do?

**Comment by saeidalidadi** [comment]
I use it as bellow.
```javascript
<script src="/modules/moment/moment.min.js"></script>
<script src="/modules/moment-jalaali/build/moment-jalaali.js"></script>
```

**Comment by alitaheri** [comment]
@behrang This is related to the build system, not the code. I think this needs your attention.

**Comment by behrang** [comment]
Seems to be related to #134. I changed build script a little. Someone please test the result after  pulling from master.

**Comment by essivision** [comment]
after add this code 
```
<script src="/plugins/moment/moment.min.js"></script>
<script src="/plugins/moment-jalaali/build/moment-jalaali.js"></script>
```
error me again:
```
Uncaught Error: failed to require "../moment"
    at require (moment-jalaali.js:14)
    at symbolMap.1 (moment-jalaali.js:318)
    at moment-jalaali.js:321
    at require (moment-jalaali.js:18)
    at moment-jalaali.js:426
    at require (moment-jalaali.js:18)
    at moment-jalaali.js:1328
    at moment-jalaali.js:1330
require @ moment-jalaali.js:14
symbolMap.1 @ moment-jalaali.js:318
(anonymous) @ moment-jalaali.js:321
require @ moment-jalaali.js:18
(anonymous) @ moment-jalaali.js:426
require @ moment-jalaali.js:18
(anonymous) @ moment-jalaali.js:1328
(anonymous) @ moment-jalaali.js:1330

```

**Comment by behrang** [comment]
In #134 this line is added:
```
require('moment/locale/fa')
```

Inside `fa` module, there is a line for requiring `../moment`. So that is going to work in node.js environment, unless we also define `../moment`.

In #138 that require line is removed. So that fixes the problem.

Also I built the standalone version again, so it includes the removal of that require statement.

It should be fixed now. I close this. Feel free to open it again if anyone find any problems.
