### ISSUE TITLE
jDaysInMonth param doesn't match with real month order

### ISSUE THREAD

**Issue by essivision** [jalaali/moment-jalaali#139]
In your documentation said to get days of specific number, we should use  `moment.jDaysInMonth(1394, 11)` .  In this example I get `Esfand` days with enter 11. It's not true, it should be 12. Why number of month doesn't match with real month order.

```
moment.jDaysInMonth(1395, 11) // 30
moment.jDaysInMonth(1394, 11) // 29
```

**Comment by alitaheri** [comment]
It's just [javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date).

**Comment by essivision** [comment]
Momentjs itself isn't like this. Why?
