### ISSUE TITLE
how to make this momentjs driven persian

### ISSUE THREAD

**Issue by myehrajat** [jalaali/moment-jalaali#140]
http://www.daterangepicker.com/#examples
i wnat to make this script persian for my project how to do this i have repalced all functions as your document but not worked

**Comment by alitaheri** [comment]
It's not that easy. And not an issue with moment-jalaali. I refer you to my implementation on a [utility library](https://github.com/alitaheri/material-ui-pickers-jalali-utils) used to implement persian support for [material-ui-pickers](https://material-ui-pickers.firebaseapp.com/localization/persian)
