### ISSUE TITLE
خطا در sequelize

### ISSUE THREAD

**Issue by Hesamp** [jalaali/moment-jalaali#145]
سلام 
وقتی من از مومن جلالی استفاده میکنم 
دچار خطا میشه
و تاریخ ورود در سیستم رو به فارسی بر میگردونه کلا 
`{
"result": false,
"data": {},
"error": {
"code": "1",
"message": "Incorrect datetime value: '۲۰۱۸-۰۶-۱۷ ۰۵:۳۲:۵۴' for column 'createdAt' at row 1",
"messageFlag": false
},
"status": 400
}`

**Comment by behrang** [comment]
More information is needed.

**Comment by Hesamp** [comment]
از کتابخانه sequlize استفاده میکنم و یک Dependencie به moment داره 
و وقتی از loadPersian در یک جای دیگه استفاده میکنم و usePersianDigits را true قرار میدم
در کتابخانه sequelize موقع ایجاد و به روز رسانی یک سند با خطا رو به رو میشه و مقدار تاریخ را با کارکتر فارسی بر میگردونه !
