### ISSUE TITLE
TypeError: Cannot read property 'humanize' of undefined on version 0.7.4

### ISSUE THREAD

**Issue by sajaddp** [jalaali/moment-jalaali#147]
Hi,
I got this error on version 0.7.4 while using `fromNow()`.
`TypeError: Cannot read property 'humanize' of undefined`
is there any way to fix it?

**Comment by nicoosokhan** [comment]
have same problem!

**Comment by behrang** [comment]
Provide some sample data. And also tell us where you are using it? Inside browser? In node.js?

**Comment by behrang** [comment]
```js
var moment = require('./')
moment('2018-07-14 17:48:04').fromNow() // => '8 days ago'
```

Tested on a fresh clone and npm install. Still need more info. Can you test it on moment (not moment-jalaali) and provide the results?

**Comment by sajaddp** [comment]
When I using 
```
import moment from 'moment';
moment.locale('fa');
let date = moment(dynamicDate).fromNow();// ex: dynamicDate= `2018-07-14 17:48:04`
console.log(date);
```
Works without error, also when I try
```
import moment from 'moment-jalaali'
let date = moment(myDynamicDate).fromNow();// ex: myDynamicDate= `2018-07-14 17:48:04`
console.log(date);
```
It works, but when I use
```
import moment from 'moment-jalaali'
moment.loadPersian({dialect: 'persian-modern'});
let date = moment(myDynamicDate).fromNow();// ex: myDynamicDate= `2018-07-14 17:48:04`
console.log(date);
```
The problem is occurred.

**Comment by behrang** [comment]
I tested it with your samples and it works on a clean checkout of moment-jalaali. I think you might have a dependency issue here with some other thing.

If you want to be sure, just clone moment-jalaali in a new directory:
```
git clone git@github.com:jalaali/moment-jalaali.git
```

Then change to that directory and run `npm i`.

Then start node: `node` and run this code:
```
var moment = require('./')
moment.loadPersian({dialect: 'persian-modern'})
let date = moment('2018-07-14 17:48:04').fromNow()
console.log(date)
```

You should see something like `9 روز پیش`.

If you get this, then there should be a dependency issue with your own project.

**Comment by sajaddp** [comment]
I think you didn't put enough time to check Moment new API.

**Comment by Anisi** [comment]
I have same issue in 0.8.3 version

**Comment by rezaHashemi8139** [comment]
just add 
`import "moment/locale/fa";`

to your file
