### ISSUE TITLE
مشکل ۲ فروردین در ios

### ISSUE THREAD

**Issue by dadwic** [jalaali/moment-jalaali#150]
@behrang @mousavian @novid @alisinabh @aaghamohammadi @alitaheri 
سلام دوستان
تقویم جلالی روی آیفون در روز ۲ فروردین هر سال مشکل داره

**Comment by alisinabh** [comment]
سلام و با اجازه از دوستان

اگه از پیاده سازی سوییفت استفاده میکنید لطفا اگه ممکنه این مشکل رو به لینک زیر منتقل کنید.

و اینکه لطفا منظورتون رو از مشکل داره دقیق تر اعلام کنید. مثلا ارور میده؟ محاسبه اشتباه انجام میده یا هر مشکل دیگه ای

ممنون و شب خوش

[https://github.com/jalaali/SwiftJalaali/issues](https://github.com/jalaali/SwiftJalaali/issues)

**Comment by dadwic** [comment]
ممنونم از توجه شما
نه منظورم روی مرورگر بود
`{jMoment("2017-03-22").format("jD jMMMM jYYYY")}`
[codesandbox test](https://codesandbox.io/s/54262l8qzx) خروجی این کد روی مرورگرهای آیفون بازکنید بجای ۲فروردین میزنه ۱ فروردین

روی مرورگرهای مک و بعضی تبلت های اندرویدی هم ۲ فرودین انتخاب کنید سه فروردین هم انتخاب میشه
هیچ اروری هم داده نمیشه 

تشکر

**Comment by behrang** [comment]
معمولا این مشکل به دلیل تغییر ساعت در روز ۱ فروردین هست. برای پیدا کردن مشکل، ساعت و
Timezone
را هم چاپ کنید تا بهتر مشکل مشخص شود:

https://codesandbox.io/s/xo3w5kr72z

کد بالا را روی مرورگر های مختلف باز کنید و نتیجه را بفرستید.

**Comment by dadwic** [comment]
سلام ممنون از راهنماییتون
خروجی‌ با مرورگرهای مختلف
`1 Farvardin 1396 23:00 +03:30` [ios11.4: chrome,safari,firefox]
`2 Farvardin 1396 01:00 +04:30` [mac10.11: chrome,firefox]
`1 Farvardin 1396 23:00 +03:30` [mac10.11: safari]
`2 Farvardin 1396 01:00 +04:30` [android7: chrome,firefox,default browser]

**Comment by behrang** [comment]
همین اطلاعات رو بدون
moment-jalaali
و فقط با
moment
میشه بفرستید؟

**Comment by dadwic** [comment]
متأسفانه الان دسترسی ندارم 
شب حتما میفرستم

**Comment by dadwic** [comment]
`21 March 2017 23:00 +03:30` [ios11.4: chrome,safari,firefox]
`21 March 2017 23:00 +03:30` [mac10.11: safari]
`22 March 2017 01:00 +04:30` [mac10.11: chrome,firefox]
`22 March 2017 01:00 +04:30` [android7: chrome,firefox,default browser]

**Comment by behrang** [comment]
این داده ها نشان میدهد که مشکل در الگوریتم تبدیل نیست و در
Timezone
است. چون هم
moment و هم moment-jalaali
هر دو یک رفتار را دارند.

شاید با کمک
moment-timezone
بتوانید مشکل را حل کنید.

اگر شد اینجا اطلاع دهید.

سپاس

**Comment by behrang** [comment]
خواهش میکنم.
