### ISSUE TITLE
unix date converting return invalid value for some dates

### ISSUE THREAD

**Issue by spostad7** [jalaali/moment-jalaali#152]
I want to convert birthday input to unix timestamp. The problem is that it converts to invalid Unix timestamp when I enter birthYear for example '1331'.

Here's my code:
`
const birthDateInput = birthObj.birthYear/birthObj.birthMonth/birthObj.birthDay;`
`
const birthdate = Moment(birthDateInput, 'jYYYY/jM/jD').format('X');
`

The result for '1331/2/13' is:
`-557465400`

**Comment by behrang** [comment]
You are dividing numbers!

Use something like:
```
const birthDateInput = birthObj.birthYear + '/' + birthObj.birthMonth + '/' + birthObj.birthDay
```

**Comment by spostad7** [comment]
@behrang 
I use es6 string interpolation. The input string is correct, I just wrote it here like this to wrap in code block

here's my actual birthday:
`
const birthDateInput = `\``${birthObj.birthYear}/${birthObj.birthMonth}/${birthObj.birthDay}`\``;
`

**Comment by behrang** [comment]
Ok, what do you expect the result to be?

It's before 1970 so it should be a negative number.
