### ISSUE TITLE
strange behavior 

### ISSUE THREAD

**Issue by unosbaghaie** [jalaali/moment-jalaali#153]
hi 

I have used datepicker , when I open and select a date to insert, the values are in jalaali date, 
then i open edit form and save . the dates are in jalaali 
but when I open  edit form, and change the date, date value is in Gregorian.

why its behavior is like that ?

**Comment by behrang** [comment]
Which project are you using? This project does not have any date picker.

**Comment by unosbaghaie** [comment]
oh my bad. I use `ng2-jalali-date-picker`
