### ISSUE TITLE
All moment locales are loaded in the built version

### ISSUE THREAD

**Issue by faridv** [jalaali/moment-jalaali#157]
I'm using moment-jalaali in a typescript/webpack project and building my project in production mode, I can see all moment locales are present in the bundled js file and they are increasing the output file size too much. How can I disable loading them in the production build version?

**Comment by faridv** [comment]
I'm just using moment-jalaali and AFAIK moment itself is being loaded as dependency of moment-jalaali. Assuming I was using moment, it has a moment package and a moment-locales package which I can remove. But with only moment-jalaali I don't know how to do that.

**Comment by behrang** [comment]
Reopened for now, but I can't help with it. Maybe others can help you.

**Comment by faridv** [comment]
I found the solution, so for anyone else who might face the same problem here is the solution.
Adding following line to `webpack.config.js` will remove all moment locale files which are all loaded by default except Persian (fa):
`new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /fa/)`
