### ISSUE TITLE
 moment.jDaysInMonth(1397,11) ==29 ??

### ISSUE THREAD

**Issue by Arshiamidos** [jalaali/moment-jalaali#164]

**Comment by Arshiamidos** [comment]
and also jmoment('1397-12-31').isValid() ==true

**Comment by Arshiamidos** [comment]
i saw the source code ;
in jDaysInMonth start from 0 for (FARVARDIN) and calculate to 11 (ESFAND).  
https://github.com/jalaali/moment-jalaali/blob/de70673bb67c8015cd0e6824e4e7c539e21b9194/index.js#L758.   
in this line .  
if month ==11 we must return 30

**Comment by behrang** [comment]
Why?

**Comment by Arshiamidos** [comment]
did you test that?
BTW i wrote adaptor for mine to handle this !
base on choosen persian month and if year was leap .
