### ISSUE TITLE
Wrong conversion for 02/01/1398 in iOS devices

### ISSUE THREAD

**Issue by farzadso** [jalaali/moment-jalaali#165]
Hi,

Thanks for your awesome library. I've been using it for a pretty long time. Unfortunately a bug was reported regarding a wrong date conversion happening only in iOS devices. I didn't have time to track down the issue. But if you want to replicate it, this is the code : 

```javascript
var momentJalaali = require("moment-jalaali")

console.log(momentJalaali('2019-03-22T00:00:00').format('jYYYY/jMM/jDD'))
```

This should result in : `"1398/01/02"`.

There's no problem on desktops and Android devices : 

<img width="628" alt="screen shot 2019-02-11 at 11 16 45 am" src="https://user-images.githubusercontent.com/19854715/52550722-89dded80-2dee-11e9-941a-e9db2233f92c.png">

Once run on an iOS device, the date switches from 01/01 to 01/02 in a blink of an eye. I can also provide a link where this blinking happens.

Here's a jsfiddle which has the same code (refer to line 1228) : 

https://jsfiddle.net/k0ragpzh/

Run on an iOS device : 👇

![img_9385](https://user-images.githubusercontent.com/19854715/52550827-0e307080-2def-11e9-9d77-a6be1337300b.PNG)

Let me know if there's anything I could do to help.

Regards.

**Comment by farzadso** [comment]
What I did to temporarily solve it was to use `moment.utc()` instead of plain old `moment()`

This solved the issue for the time being

**Comment by alitaheri** [comment]
This isn't an issue with moment-jalaali or moment itself. the string you're providing the function with is not standard. either use standard string. or provide formatting.

https://stackoverflow.com/a/5324266

without the `Z` at the end it simply parses it as it's in the current timezone. please take your time and study how dates work in javascript and always use the standard string `2019-02-16T06:48:42Z` or specify format to the moment function

**Comment by farzadso** [comment]
Thanks for the reply.

I still have a question if it's ok. Why did it work correctly on my Android and Desktop devices with the same timezone settings?

**Comment by alitaheri** [comment]
@farzadso I sent you the link for that purpose. Moment asks the js native Date object to parse first before running it's own heuristics. and the native Date object behaves differently across platforms. that's why it's discouraged:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

> Note: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

note the "...are treated as UTC, not local". this means, some platforms will parse in UTC and some will parse in LOCAL TIME. so, never rely on it, always provide VALID "ISO 8601" string or provide format string.

**Comment by farzadso** [comment]
@alitaheri Thanks for the info mate.
