### ISSUE TITLE
فک کنم این عنوان  باید بشه Mordad به جای Amordaad

### ISSUE THREAD

**Issue by sadeghiphp** [jalaali/moment-jalaali#172]
https://github.com/jalaali/moment-jalaali/blob/de70673bb67c8015cd0e6824e4e7c539e21b9194/build/moment-jalaali.js#L518

**Comment by behrang** [comment]
- https://github.com/jalaali/moment-jalaali#options
- https://github.com/jalaali/moment-jalaali/issues/101
- https://github.com/jalaali/moment-jalaali/issues/39
