### ISSUE TITLE
problem in add day

### ISSUE THREAD

**Issue by marmulack** [jalaali/moment-jalaali#173]
Hi and thank for your good library

the problem is when need add day to a date in loop. show below code:

> let monthMomentObject= moment('1398/01/31', 'jYYYY/jM/jD');
for (let weekIndex = 0; weekIndex < 5; weekIndex++) {
   week = [];
   for (let dayIndex = 0; dayIndex < 7; dayIndex++) {
      let day = (weekIndex * 7) + dayIndex;
      console.log('day: ' + day);
      console.log(monthMomentObject.add(day, 'day').format('jYYYY/jMM/jDD HH:mm:ss'));
   }
}

this source should to return number 0 to 34 is true and for day number and 1398/01/31 to 1398/03/03 for date. for more debug for time zone problems i add time and all is zero. the wrong response in console are there:

> day: 0 
1398/01/31 00:00:00 
day: 1 
1398/01/02 00:00:00 
day: 2 
1398/01/03 00:00:00 
day: 3 
1398/01/04 00:00:00 
day: 4 
1398/01/05 00:00:00 
day: 5 
1398/01/06 00:00:00 
day: 6 
1398/01/07 00:00:00 
day: 7 
1398/01/08 00:00:00 
day: 8 
1398/01/09 00:00:00 
day: 9 
1398/01/10 00:00:00 
day: 10 
1398/01/11 00:00:00 
day: 11 
1398/01/12 00:00:00 
day: 12 
1398/01/13 00:00:00 
day: 13 
1398/01/14 00:00:00 
day: 14 
1398/01/15 00:00:00 
day: 15 
1398/01/16 00:00:00 
day: 16 
1398/01/17 00:00:00 
day: 17 
1398/02/18 00:00:00 
day: 18 
1398/03/19 00:00:00 
day: 19
1398/04/20 00:00:00 
day: 20 
1398/05/21 00:00:00
day: 21 
1398/06/22 00:00:00 
day: 22 
1398/07/23 00:00:00 
day: 23 
1398/08/24 00:00:00 
day: 24 
1398/09/25 00:00:00 
day: 25 
1398/10/26 00:00:00 
day: 26 
1398/11/27 00:00:00 
day: 27 
1398/12/28 00:00:00 
day: 28 
1399/01/29 00:00:00 
day: 29 
1399/02/30 00:00:00 
day: 30 
1399/03/31 00:00:00 
day: 31 
1399/05/01 00:00:00 
day: 32 
1399/07/02 00:00:00
day: 33
1399/09/04 00:00:00
day: 34
1399/11/05 00:00:00

so you can see where day is 1 the wrong day is 1398/01/02 and should be 1398/02/01 in next where day is 17 the date is 1398/02/18 and should be 1398/02/17 so then after that the problem is more. see the month and year.

so i try with `.zone('+4:30')` and `.utcOffset('+4:30')` and any thing not changed in response.

where is problem???

**Comment by behrang** [comment]
When adding and subtracting from moment, it will change and mutate the original object. I tested your code, and it returned a different result. Anyway, the problem is when you add 1 day to it, the `monthMomentObject` is now in the new date not the original date. When you add 2, it will be added to the previous 1, and totally adds 3 days.

Here is your code, a little changed, so that it shows the result that you want:

```
let moment = require('./')
for (let weekIndex = 0; weekIndex < 5; weekIndex++) {
  week = [];
  for (let dayIndex = 0; dayIndex < 7; dayIndex++) {
    let monthMomentObject= moment('1398/01/31', 'jYYYY/jM/jD');
    let day = (weekIndex * 7) + dayIndex;
    console.log('day: ' + day);
    console.log(monthMomentObject.add(day, 'day').format('jYYYY/jMM/jDD HH:mm:ss'));
  }
}
```

**Comment by marmulack** [comment]
Hi and thanks for your fast answer

you say right but the problem is not solved, please do more attention on first day. if i remove loop and just create a data by moment in 1398/01/31 and add 1 day to it. that should be get to 1398/02/01 but get to 1398/01/02. the problem is not for date formatting and format set to `jYYYY/jMM/jDD`. if change day add number to 2 that should be get at 1398/02/02 but get to 1398/01/03. so that is WRONG!!! this is my problem.
