### ISSUE TITLE
moment-jalaali return wrong date

### ISSUE THREAD

**Issue by AprinDev** [jalaali/moment-jalaali#179]
jmoment` return wrong date 
when i pass diffrent date to it , it return wrong . even when i pass data from 3 consecutive days
return me date from diffrent month

when i use 
`console.log( moment('2019-10-22T00:00:00.000', 'YYYY-M-D HH:mm:ss').endOf('jMonth').format('jYYYY/jM/jD HH:mm:ss'));console.log( moment('2019-10-23T00:00:00.000', 'YYYY-M-D HH:mm:ss').endOf('jMonth').format('jYYYY/jM/jD HH:mm:ss'));console.log( moment('2019-10-24T00:00:00.000', 'YYYY-M-D HH:mm:ss').endOf('jMonth').format('jYYYY/jM/jD HH:mm:ss'));`

in console return :
1398/7/30 23:59:59
1398/8/30 23:59:59
1398/8/30 23:59:59

**Comment by behrang** [comment]
That is the expected behavior. You are asking for the end of Jalaali month, and the days you are testing are on the border of a Jalaali month.
