### ISSUE TITLE
moment.localeData is not a function

### ISSUE THREAD

**Issue by erfanatp** [jalaali/moment-jalaali#182]
Hi I use it in React `16.8.6`.

```
.
.
.
import moment from 'moment-jalaali';
import fa from 'moment/src/locale/fa';
.
.
.
  useEffect(() => {
    moment.locale('fa', fa);
    moment.loadPersian();
  }, []);
.
.
.
```
It returns an error:

> 
> index.js?a67b:197 Uncaught TypeError: moment.localeData is not a function
>     at eval (index.js?a67b:197)
>     at Object../node_modules/moment-jalaali/index.js (vendors~main.chunk.js:4637)
>     at __webpack_require__ (main.js:787)
>     at fn (main.js:150)
>     at eval (index.js:11)
>     at Module../app/containers/PayResult/index.js (main.js:1632)
>     at __webpack_require__ (main.js:787)
>     at fn (main.js:150)
>     at eval (index.js?b8af:1)
>     at Module../app/containers/App/index.js (main.js:1188)

and

> [HMR] bundle has 1 warnings
> client.js?f33d:189 ./node_modules/moment/src/lib/locale/locales.jsModule not found: Error: Can't resolve './locale' in '/Users/Erfan/WebstormProjects/myproject/node_modules/moment/src/lib/locale'

**Comment by alitaheri** [comment]
This could be related to how you're importing.

try `import * as moment from 'moment-jalaali';` and tell me what happens.

**Comment by erfanatp** [comment]
@alitaheri I just use this import without using it. But I get the same error.
`import * as moment from 'moment-jalaali';`

consider I use [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate).

**Comment by alitaheri** [comment]
You might wanna debug it yourself to see what exactly is being imported. there isn't much I can help you with. or provide a minimal zipped app that has this issue.

**Comment by erfanatp** [comment]
@alitaheri Finally, I found the solution!
I should change the order in `internals/webpack/webpack.base.babel.js`

From:

```
mainFields: [
  'browser',
  'jsnext:main',
  'main',
],
```

To

```
mainFields: [
  'browser',
  'main',
  'jsnext:main',
],
```

**Comment by reza3vi** [comment]
file:
/node_modules/moment-jalaali/index.js

replace: (line 4)

var moment = require('moment')
to
var moment = require('moment/moment')
