### ISSUE TITLE
error with the last day of SHAHRIVAR

### ISSUE THREAD

**Issue by pouyamiralayi** [jalaali/moment-jalaali#185]
Hi there! as with other jalali libraries, i have faced this issue once again using this library.
the produced date for 31/6 (last day of SHAHRIVAR) is producing wrong Gregorian date.
storing the result Gregorian date will produce `date/time field out of range` error inside postgres db.
thanks.

**Comment by behrang** [comment]
What was the input? What was the output?

Did you consider months starting from 0?

**Comment by pouyamiralayi** [comment]
hi @behrang the problem was my postgres db side. sorry for bothering. the library is fine. i am closing this now.
thanks for your support.
