### ISSUE TITLE
Moment-jalali.js having month names with wrong spelling names

### ISSUE THREAD

**Issue by kalvagopinath** [jalaali/moment-jalaali#190]
Hi, Moment-jalali.js having month names with wrong spelling names. fixed it with replacing after reading the value in my controller. any other options ...?

currently -->
_jMonths: [ 'Farvardin'
              , 'Ordibehesht'
              , 'Khordaad'
              , 'Tir'
              , 'Amordaad'
              , 'Shahrivar'
              , 'Mehr'
              , 'Aabaan'
              , 'Aazar'
              , 'Dey'
              , 'Bahman'
              , 'Esfand'
              ]

expected-->

_jMonths: [ 'Farvardin'
              , 'Ordibehesht'
              , 'Khordad'
              , 'Tir'
              , 'Mordad'
              , 'Shahrivar'
              , 'Mehr'
              , 'Aban'
              , 'Azar'
              , 'Dey'
              , 'Bahman'
              , 'Esfand'
              ]

**Comment by behrang** [comment]
Read #101.
