### ISSUE TITLE
daysInMonth in not defined

### ISSUE THREAD

**Issue by javadbat** [jalaali/moment-jalaali#191]
I'm writing a date picker that uses Jalali moment and need both Jalali and gregorian format at the same time.
while in Jalali `jDaysInMonth()` work without problem i cant use standard moment `daysInMonth` method

**Comment by behrang** [comment]
These methods work completely differently. Read the docs for `daysInMonth` here:
https://momentjs.com/docs/#/displaying/days-in-month/

**Comment by behrang** [comment]
Closing this, feel free to reopen if this doesn't solve the problem.
