### ISSUE TITLE
Incorrect date convertion

### ISSUE THREAD

**Issue by AShkurpelo** [jalaali/moment-jalaali#199]
I converted dates for +- 5 years interval from now to be sure it matches Hijri dates given by MS Umm al-Qura calendar and found 1 mismatch:
`moment('2024-12-02').format('YYYY-M-D [is] iYYYY-iM-iD') // 2024-12-2 is 1446-5-30`
But according to http://www.ummulqura.org.sa and other resources, it's 1446-6-1

**Comment by behrang** [comment]
I think you are looking for another repo. This is a Jalaali repo, converting to/from Persian calendar system. It also works with `j` prefixes, not `i`, and currently we are in year 1398, not 1442.

**Comment by AShkurpelo** [comment]
Oh, Sorry, I was looking into moment-jalaali and moment-hijri at the same time and missed browser tabs. Closing the issue. Sorry again.
