### ISSUE TITLE
نام درست گاهشمار

### ISSUE THREAD

**Issue by vahid-sohrabloo** [jalaali/moment-jalaali#20]
با سلام خدمت دوست عزیز
شاید این موضوع خیلی هم مهم نباشد ولی خواستم اشاره ای داشته باشم شاید برای شما مهم باشد.
نام گذاری شما برای نام این گاهشمار به جلالی اشتباه است.
همانگونه که شما هم می‌دانید گاهشماری فعلی و رسمی ایران گاهشمار هجری خورشیدی است که در انگلیسی با نام
Persian Calendar 
میشناسند و در واقع گاهشمار جلالی یک گاهشمار با مبنای شروع تاریخ متفاوت و حتی طول ماه‌ها و حتی نام ماه‌های متفاوتی است.
گاهشمار رسمی ایران نحوه محاسبه بر مبنای همان گاه شمار جلالی است با این تفاوت که مبنای شروع تاریخ و طول ماه‌ها و همچنین نام‌ ماه‌های متفاوتی دارد.

**Comment by amastaneh** [comment]
+1

**Comment by tomvolek** [comment]
+1

**Comment by behrang** [comment]
Right now, we have an organization in GitHub named "Jalaali" and it is available at "https://github.com/jalaali" and sub projects are below it, for example `jalaali-js` is available at "https://github.com/jalaali/jalaali-js" and `moment-jalaali` is available at "https://github.com/jalaali/moment-jalaali". 

Renaming project to "Persian" will change organization name and it's url to "https://github.com/persian" which I think is not indicating that it is a calendar project. It mostly implies that it is related to Persian language. Renaming it to "Persian Calendar" will make the url very big like "https://github.com/persian-calendar" and sub projects will get bigger too, like "https://github.com/persian-calendar/persian-calendar-js" and https://github.com/persian-calendar/moment-persian-calendar".

Also it is not a unique name for identifying the calendar algorithm and sub projects that use this algorithm.

I think the important thing here is that this algorithm is great, is correct, and also easy to implement in different languages and projects. Giving it a unique identifiable name is a good thing for this and it's sub projects.

**Comment by alitaheri** [comment]
I'm closing this since changing the name is a huge breaking change with very little benefit.
