### ISSUE TITLE
wrong week  day 

### ISSUE THREAD

**Issue by jafarpishdadi** [jalaali/moment-jalaali#200]
hello

moment("2020/03/21", 'YYYY/MM/DD')
              .format('dddd');

 return  friday    جمعه
 saturday  شنبه  correct

Just the same day
thanks

**Comment by behrang** [comment]
Hello,

This is related to summer time. When you don't include time in your input string, it is assumed to be zero, midnight. On March 21, Iran moved to summer time, and as a result, that hour doesn't exists, and it is assumed to be on the previous day:

```js
moment("2020/03/21 00:00:00+0330", 'YYYY/MM/DD hh:mm:ssZ').format('dddd') // Saturday

moment("2020/03/21 00:00:00+0430", 'YYYY/MM/DD hh:mm:ssZ').format('dddd') // Friday
```

You want the first result, but you get the second. To fix the problem on every day, including the border days where timezone changes occur, add a few hours to your input string and parse format:

```js
moment("2020/03/21 12:00:00+0430", 'YYYY/MM/DD hh:mm:ssZ').format('dddd') // Saturday
```
