### ISSUE TITLE
How Get Persian Name Month's ?

### ISSUE THREAD

**Issue by mohsen77sk** [jalaali/moment-jalaali#201]
How Get Persian Name Month's ?

```
import * as momentJalaali from 'moment-jalaali';
momentJalaali.loadPersian({ usePersianDigits: true, dialect: 'persian-modern' });
momentJalaali.localeData('fa').months();
```
return: ژانویه,فوریه,مارس,آوریل,مه,ژوئن,ژوئیه,اوت,سپتامبر,اکتبر,نوامبر,دسامبر

**Comment by behrang** [comment]
It is not implemented like the `months` method in `moment`. For now, you can use this:

```
moment.localeData('fa')._jMonths
```

Or you may add a method to the source and send a pull request.
