### ISSUE TITLE
i want show 1399/01/02 instated of 1399/1/2

### ISSUE THREAD

**Issue by sam9010** [jalaali/moment-jalaali#204]
i want show 1399/01/02 instated of 1399/1/2
i mean 2 character for day and month no 1 character

**Comment by matinzd** [comment]
use `jYYYY/jMM/jDD` -> 1399/01/02
if you use `jYYYY/jM/jD` you will get something like this -> 1398/1/2

**Comment by sam9010** [comment]
@matinzd thanks a lot
