### ISSUE TITLE
moment.localeData is not a function

### ISSUE THREAD

**Issue by m-jooibar** [jalaali/moment-jalaali#207]
Hello i install vue-persian-datetime-picker package.
when i load page , i have one error in my google console . 

>Uncaught TypeError: moment.localeData is not a function
    at eval (index.js:197)
    at Object../node_modules/vue-persian-datetime-picker/node_modules/moment-jalaali/index.js (wallets.js:2459)
    at __webpack_require__ (wallets.js:20)
    at eval (vue-persian-datetime-picker.js:1)
    at eval (vue-persian-datetime-picker.js:1)
    at Object../node_modules/vue-persian-datetime-picker/dist/vue-persian-datetime-picker.js (wallets.js:2448)
    at __webpack_require__ (wallets.js:20)
    at eval (wallets.js:7)
    at Module../modules/acc/components/walletmanager/wallets/wallets.js (wallets.js:241)
    at __webpack_require__ (wallets.js:20)

I'm confused . I tried to solve the problem. But it didn't happen
can you help me ? :(

**Comment by m-jooibar** [comment]
i tried #182  problem solutions.  but my problem not resolved .

**Comment by m-jooibar** [comment]
بعد از  تلاش فراوان  مشکل رو  حل  کردم .  
جواب رو  میذارم  واسه  دوستانی که اگه  مشکل  مشابه داشتند  کمتر  اذیت بشن   .  
ببینید از آخرین ورژن  پکیج های  زیر استفاده میکنیم :   

```
  "dependencies": {
.
.
    "moment-jalaali": "^0.7.4",
    "vue-moment": "^4.1.0",
    "vue-persian-datetime-picker": "^2.1.5",
.
.
  },
```

بعد تو فایل اصلی این کدها رو  مینویسیم :  

```
Vue.use(require('vue-moment'));
Vue.use(require('moment-jalaali'));

import VuePersianDatetimePicker from 'vue-persian-datetime-picker';
Vue.component('date-picker', VuePersianDatetimePicker);
```
 
و تنظیمات webpach.config.js  رو هم  مثل کد زیر  انجام میدیم  :   

```
const webpack = require('webpack/lib/webpack');

module.exports = {
.
.
    plugins: [
.
.
        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
.
.
    ],
.
.
}

```

و و و و   نکته اصلی اینجاست .  میرید تو  فولدر 

node_modules 

و بعد تو  فولدر 

moment-jalaali

و اونجا در خط 4 کد رو  به این صورت تغییر میدید :

```
module.exports = jMoment

var moment = require('moment/moment')
  , jalaali = require('jalaali-js')

```
یعنی دقیقا مورد بحث این هستش :  

```
var moment = require('moment/moment')
```
سعی کردم  خیلی دقیق بگم .  کسی مشکل داشت  همینجا  کامنت بذاره .  موفق باشید

**Comment by reza3vi** [comment]
file:
/node_modules/moment-jalaali/index.js

replace: (line 4)

var moment = require('moment')
to
var moment = require('moment/moment')

**Comment by hosni** [comment]
For anyone using [`vite`](https://github.com/vitejs/vite), this worked for me:
```js
export default defineConfig({
    resolve: {
        alias: {
            'moment/locale/fa': path.resolve(__dirname, 'node_modules/moment/locale/fa.js'),
            'moment/moment': path.resolve(__dirname, 'node_modules/moment/moment.js'),
            'moment': path.resolve(__dirname, 'node_modules/moment/moment.js'),
        },
    },
});
```

**Comment by VitalyLitvinov74** [comment]
> For anyone using [`vite`](https://github.com/vitejs/vite), this worked for me:
> 
> export default defineConfig({
>     resolve: {
>         alias: {
>             'moment/locale/fa': path.resolve(__dirname, 'node_modules/moment/locale/fa.js'),
>             'moment/moment': path.resolve(__dirname, 'node_modules/moment/moment.js'),
>             'moment': path.resolve(__dirname, 'node_modules/moment/moment.js'),
>         },
>     },
> });

is help for me thanks!

**Comment by hosni** [comment]
> > For anyone using [`vite`](https://github.com/vitejs/vite), this worked for me:
> > export default defineConfig({
> > resolve: {
> > alias: {
> > 'moment/locale/fa': path.resolve(__dirname, 'node_modules/moment/locale/fa.js'),
> > 'moment/moment': path.resolve(__dirname, 'node_modules/moment/moment.js'),
> > 'moment': path.resolve(__dirname, 'node_modules/moment/moment.js'),
> > },
> > },
> > });
> 
> is help for me thanks!

Your welcome! 🔥
