### ISSUE TITLE
loadPersian

### ISSUE THREAD

**Issue by ImanMh** [jalaali/moment-jalaali#21]
Hi,
I pulled your repo via bower and tried to use `moment.loadPersian()` in my script. It gives me the following error: 

```
Uncaught TypeError: undefined is not a function
```

**Comment by mirshahreza** [comment]
> Anyway, we decided to use your plugin as a bundle in our project because we want it everywhere and it works in that environment just like what we expect. Thank you.

Please more explain how you use it as a bundle. creating the bundle and configuration for requirejs
Thanks
