### ISSUE TITLE
Error: Cannot find module './locale'

### ISSUE THREAD

**Issue by polbadman** [jalaali/moment-jalaali#213]
سلام به همه:
من این کدو توی  راکت وارد می کنم و خطا می ده؟
import moment from "moment-jalaali";
import fa from "moment/src/locale/fa";
moment.locale("fa", fa);
moment.loadPersian();

...

{moment(product.createdAt).fromNow()}

**Comment by DivineAlien** [comment]
i have the same issue. i tried also version 0.7.3 but it's not working.

```
npm install moment-jalaali@0.7.3 
```
still the same

**Comment by DivineAlien** [comment]
the only way to this problem for me was.
changing the line:
```
 import fa from "moment/src/locale/fa";
```
to 
```
import fa from "moment/locale/fa";
```

is this a good practice?! @behrang 
hosseinmd:patch-1
