### ISSUE TITLE
Show En digit not Persian Digit

### ISSUE THREAD

**Issue by davodaslanifakor** [jalaali/moment-jalaali#239]
Here when I use show format by this method for e.g: 
```
m.format('YYYY-MM-DD')

```
result become like this 
``` 
۲۰۲۲-۰۸-۰۱
```
But I expect to become like this 
```
2022-08-01
```
Have any solutions?

**Comment by mohamad4j** [comment]
Hi. You should add this
`davood aslani fakor, [8/2/22 10:10 AM]
const moment = require('moment-jalaali')
moment.loadPersian({ usePersianDigits: false })`

**Comment by mohamad4j** [comment]
Hi, You should use this
`const moment = require('moment-jalaali')
moment.loadPersian({ usePersianDigits: false })`
