### ISSUE TITLE
moment.unix not work

### ISSUE THREAD

**Issue by pajooh** [jalaali/moment-jalaali#25]
after struggling for many hours on this:
```js
moment.unix(timestamp/1000).format('jYYYY/jM/jD')
```
i found that simply it does not work. but this one do:
```js
moment(Date(timestamp)).format('jYYYY/jM/jD')
```

**Comment by behrang** [comment]
Does it work with moment alone?

**Comment by pajooh** [comment]
@behrang what do you mean by "alone"?
i'm using this package inside browser (including the script after moment itself)

**Comment by behrang** [comment]
I mean test it without moment-jalaali included on page and without jYYYY jM jD formatting.

**Comment by pajooh** [comment]
the normal formatting (without ```j```) works as expected

**Comment by behrang** [comment]
Fixed. Update and test again.
