### ISSUE TITLE
Why weeks start from یکشنبه?

### ISSUE THREAD

**Issue by A2DNEW** [jalaali/moment-jalaali#250]
Hi
I use this code:

```
import moment from 'jalali-moment';
const array = moment.localeData('fa').weekdays();
console.log(array);
```
And this code return wrong array.
Because starts with یکشنبه.

**Comment by behrang** [comment]
This is the locale data, which must match the English version for translation of the days of the week. Returning first day of week as Saturday is out of the scope of `moment-jalaali`.

**Comment by saeidRouhparvar** [comment]
moment().locale('fa').format('ddd')
Apar Chaldir :(
