### ISSUE TITLE
what is require('moment/moment') ?

### ISSUE THREAD

**Issue by shomid** [jalaali/moment-jalaali#251]
In line 420, there is a require('moment/moment') command that causes an error.
![Screenshot from 2023-07-08 10-08-02](https://github.com/jalaali/moment-jalaali/assets/8733354/fd997c07-e9f6-40db-877c-4b863840bcc2)

Why is the command require('moment') not used?
![Screenshot from 2023-07-08 10-08-25](https://github.com/jalaali/moment-jalaali/assets/8733354/4a9d454c-8af0-481f-b943-d98515188046)

**Comment by parsibox** [comment]
what happend?
