### ISSUE TITLE
How to compare jalaali persian dates

### ISSUE THREAD

**Issue by 1mehdifaraji** [jalaali/moment-jalaali#258]
I'm trying to use the `isAfter` function but I always get `false` from it:

```
moment("۱۴۰۲/۱۲/۲۷").isAfter("۱۴۰۲/۱۲/۲۲");
```

How can I use `isAfter` and compare jalaali dates ? Thanks in advance.
@behrang

**Comment by behrang** [comment]
Something like this:

`moment('1402/12/27', 'jYYYY/jMM/jDD').isAfter(moment('1402/12/22', 'jYYYY/jMM/jDD'))`
