### ISSUE TITLE
هنگ کردن مرور گر درهنگام استفاده

### ISSUE THREAD

**Issue by sajadonline** [jalaali/moment-jalaali#26]
سلام و وقت بخیر 
اول خواستم تشکر کنم و دوم اینکه من وقتی کد جاوا جلالی رو بارگذاری میکنم مرورگر کلا هنگ میکنه لطفا راهنمایی کنید 
ممنون

&lt;!DOCTYPE html&gt;

&lt;html&gt;
&lt;head&gt;
&lt;title&gt;jalali moment &lt;/title&gt;
&lt;meta charset="UTF-8"&gt;
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
&lt;script src="js/jquery-1.11.2.min.js"&gt;&lt;/script&gt;
&lt;script src="js/bootstrap.min.js"&gt;&lt;/script&gt;
&lt;script src="js/moment.min.js"&gt;&lt;/script&gt;
&lt;script src="js/moment-jalaali.js"&gt;&lt;/script&gt;

&lt;script src="js/bootstrap-datetimepicker.min.js"&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div class="container"&gt;
&lt;div class="row"&gt;
&lt;div class='col-sm-6'&gt;
&lt;div class="form-group"&gt;
&lt;div class='input-group date' id='datetimepicker1'&gt;
&lt;input type='text' class="form-control" /&gt;
&lt;span class="input-group-addon"&gt;
&lt;span class="glyphicon glyphicon-calendar"&gt;X&lt;/span&gt;
&lt;/span&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;script type="text/javascript"&gt;
$(function () {
moment().format('jYYYY/jM/jD')
$('#datetimepicker1').datetimepicker( );
});
&lt;/script&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by behrang** [comment]
Remove `bootstrap`, `jquery`, and `bootstrap-datepicker` and test again. It should work. Then add those dependency one by one and see what happens. I think the problem might be in `bootstrap-datepicker`.
