### ISSUE TITLE
Memory leak issue by rimraf@3.0.2 > glob@7.2.3 > inflight@1.0.6

### ISSUE THREAD

**Issue by mostafa-rio** [jalaali/moment-jalaali#261]
Dependency rimraf@3.02 uses glob@7.2.3 that causes memory leak issue since its using inflight as dependency.
according to this github issue from glob package they fixed it by removing inflight in version 8.

https://github.com/isaacs/node-glob/issues/435

Solution:
Upgrading rimraf to latest version possibly can solve this issue

**Comment by behrang** [comment]
Hey, you've also changed the structure of code and removed 2 functions. Why is that?

**Comment by EhsanKhalili** [comment]
Hi, I have the same issue:

``` npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. ```

**Comment by behrang** [comment]
Just released a new patch version and upgraded dependencies.

**Comment by EhsanKhalili** [comment]
> Just released a new patch version and upgraded dependencies.

Thank you for caring.
