### ISSUE TITLE
endOf function

### ISSUE THREAD

**Issue by beygi** [jalaali/moment-jalaali#27]
the moment's **endOf** function don't work , it just returns the current time
~~~js
moment().endOf('jMonth')
~~~
i think you never add jalaali units to the moment using **addUnitAlias** because when i comment the line that checks aliases the function wroks as expected :
~~~js
    function endOf (units) {
        //units = normalizeUnits(units);
        if (units === undefined || units === 'millisecond') {
            return this;
        }
        return this.startOf(units).add(1, (units === 'isoWeek' ? 'week' : units)).subtract(1, 'ms');
    }
~~~

**Comment by behrang** [comment]
There is no need for `addUnitAlias` since `normalizeUnits` returns the lowercased version of the unit anyway. Also, I checked it and it is working as expected and returns end of Jalaali month and year. Provide more information or example code. Also tell me your version of `moment-jalaali` and `moment`.

**Comment by beygi** [comment]
moment : version : 2.10.2
moment-jalali : 0.3.7

**Comment by beygi** [comment]
normalizeUnits from my moment is look like this :
~~~js
    function normalizeUnits(units) {
        return typeof units === 'string' ? aliases[units] || aliases[units.toLowerCase()] : undefined;
    }
~~~
and as you see it returns aliases based on input not a lowercased version of the unit

**Comment by behrang** [comment]
On version 2.10, normalizeUnit is changed, and this bug was because of that. It should be fixed.

**Comment by beygi** [comment]
so , the bug is related to moment or moment-js ?

**Comment by behrang** [comment]
It **was** related to `moment-jalaali` because of a change in a recent version of `moment`, but is is fixed now.

**Comment by beygi** [comment]
nice , thank you

**Comment by behrang** [comment]
No problem. Remember to update to version 0.3.8.
