### ISSUE TITLE
تبدیل ارقام به فارسی

### ISSUE THREAD

**Issue by mvalipour** [jalaali/moment-jalaali#29]
even after calling `moment.loadPersian()` the outcome of the `format()` has latin digit characters.

I think this is wrong. In fact even digits should be converted to their corresponding arabic/farsi equivalent.
However making this  a default behaviour will have backwards-compatibility issues, so what I suggest is an option to the `loadPersian()` method:

```
moment.loadPersian = function(convertNumbers = false)...
```

here is a code I'm using to do the conversion. (could potentially be optimised for performance, although I doubt that would even be an issue)

```
    // replcae digits
    for (var i = 0; i < 10; i++) {
      res = res.replace(new RegExp(i.toString(), 'g'), String.fromCharCode(0x06F0 + i));
    }
```

which converts `27 اردیبهشت 1394` to `۲۷ اردیبهشت ۱۳۹۴`

**Comment by behrang** [comment]
I disagree. In fact, this behaviour that you want is implemented in localization of `moment`.

I think, many places you need to be able to copy and paste formatted strings. Most places where you paste some string, cannot handle Persian digits. To be able to display digits in Persian, but also be able to copy and paste strings everywhere, I modify the font files and replace Latin digits with Persian equivalent. This way it is displayed as Persian, but behind the scene, it is an ordinary number.

As an aside, even if you don't like my approach, and want to always replace digits with Persian ones, you need to do it in other places where you display numbers, not just date formatted strings. To do that, you need another solution for replacing those numbers with Persian. In that case, it is better to pass the result of your date formats through that utility to replace digits in dates too.

The behaviour you said, is implemented in `moment`'s localization for Persian. If still you want that, you can load `moment`'s `fa` localization and bypass calling `loadPersian` method.

**Comment by mvalipour** [comment]
Hmmm, using fonts are interesting way of looking at it.

Are there any particular web fonts you use yourself that support this?

**Comment by behrang** [comment]
I don't know of any. We customized one ourselves. You can grab it from https://pfm.abplus.ir

**Comment by mvalipour** [comment]
cool, then I guess we can close this.

thanks for the really nice work BTW :)
Let me know if you ever needed collaborators for your current/future OSS work.

**Comment by behrang** [comment]
Ok, thanks.
