### ISSUE TITLE
Infinite loops when extending the library

### ISSUE THREAD

**Issue by Fardinak** [jalaali/moment-jalaali#30]
Hi,
First I wanna thank you for the great work. It's really useful.

I tried to extend the library using the conventional methods of prototyping and came across multiple infinite loops caused by using `this` to access original moment methods line `year`, `month` and `date`. As an example I reffer you to [master/index.js#L578](https://github.com/jalaali/moment-jalaali/blob/master/index.js#L578):
```javascript
j = toJalaali(this.year(), this.month(), this.date())
```
This makes it impossible to override these methods with new ones that use the base method. i.e.
```javascript
function myMoment() {
  return makeMoment();
}
extend(myMoment, moment);

myMoment.fn.year = function() {
  if (this.isJalali)
    return moment.fn.jYear.apply(this, arguments); // Infinite Loop
  return moment.fn.year.apply(this, arguments); // Infinite Loop
}

function makeMoment() {
  var m = new moment();

  function Fn() {};
  Fn.prototype = myMoment.fn
  extend(Fn, m);
  return new Fn;
}
```

**Comment by behrang** [comment]
It's the opposite. As those methods are called on `this`, it's possible to extend `moment-jalaali` by subclassing it and overriding for example the `year` method on the `prototype` and then `this.year()` will call the overridden method. The catch is, you have to use your subclass and call your methods on instances of that subclass.

**Comment by Fardinak** [comment]
What I need is, as I mentioned in #31, a general method which returns `moment.year()` or `jMoment.jYear()` depending on user configuration.
Correct me if I got you wrong, but I believe the method you mentioned helps override the `moment.year()` function, which I don't find relevant in any case!

**Comment by behrang** [comment]
You said: "This makes it impossible to override these methods." and I answered.
So if this is not relevant anymore, let's close this issue, and open another one about a different topic.

**Comment by Fardinak** [comment]
Yeah, bad phrasing I guess; but the title still applies.
I will edit the main post…

Meanwhile, are there any solutions that you could offer?

**Comment by behrang** [comment]
No, I can't. So i close this.

**Comment by Fardinak** [comment]
Oh, OK.

So, here is how I did it (for anyone else who might be interested or need that kind of functionality):
I had to create a completely new object, and write my own functions + create all the original methods from moment and bind them directly.
Here is my angular module: https://gist.github.com/Fardinak/449b4842751579eb1510
