### ISSUE TITLE
how to use momentJS with requireJS

### ISSUE THREAD

**Issue by sfakur** [jalaali/moment-jalaali#32]
hi, thanks alot for this library, but when I use it in requireJs, I face with the following error.
error: 'moment is not defined'
code lines:
 require.modules = {
        moment: { exports: moment }
    };

**Comment by behrang** [comment]
You have to add 'moment' as a dependency to your project too.

**Comment by sfakur** [comment]
dear behrang,
thank u for your reply but doesn't work. could you give me a sample.
my configuration is:
require.config({
    baseUrl: "",
    paths: {
	........
        'moment': '/Scripts/date/moment.min',
        'momentJalaali': '/Scripts/date/moment-jalaali',
	........
    },
    shim: {
	.........
        'moment': { deps: ['jquery', 'angular'] },
        'momentJalaali': { deps: ['jquery', 'angular', 'moment'], exports: "moment" },
        .........
    }
});

when I replace moment-jalaali with moment-hijri no error occured.

**Comment by ImanMh** [comment]
I think there is an issue with the internal implementation of the library that you can't make it compatible with requireJS. That would be awesome if you can fix this.

**Comment by behrang** [comment]
Yes, you are right. I don't have time right now, but I will fix it in the next version. That is why I have kept this issue open.

**Comment by ImanMh** [comment]
If anyone has the same issue I have posted a work around in my blog: 
http://jsdecorator.com/blog/post/loading-momentjs-and-its-locales-and-plugins-using-requirejs

**Comment by behrang** [comment]
Great. Thanks.

**Comment by alitaheri** [comment]
The fix is [above](https://github.com/jalaali/moment-jalaali/issues/32#issuecomment-143344533). Thanks @ImanMh

**Comment by mirshahreza** [comment]
> If anyone has the same issue I have posted a work around in my blog: http://jsdecorator.com/blog/post/loading-momentjs-and-its-locales-and-plugins-using-requirejs

the address is not available now
