### ISSUE TITLE
Year greater than 3177

### ISSUE THREAD

**Issue by afattahi54** [jalaali/moment-jalaali#33]
I found that the moment jalaali moment works for years less than 3177. Is it a must ?! 

I am using moment isValid, isSame , and other functions which get user input directly, and it is possible that user enters some invalid date. Although I can check user date manually, but I want to know if the plugin can accept larger years, may be up to 9999 !

**Comment by behrang** [comment]
The conversion algorithm works in a 3 thousand years span. So dates should be in this range to be valid. If you don't need exact validity check, you can ignore isValid and check format manually. This way you won't be able to check leap years which may not be important in that large time span.

**Comment by afattahi54** [comment]
As a matter of curiosity  ....  It seemed to me that if the algorithm works for three thousand years it should work for the rest, which seems not true ! Can you describe why this will not work after 3177 ? Or can you direct me to link which I can read more about it. 
I have see http://www.time.ir/ and https://github.com/farhadi/JalaliJSCalendar they both have year limitation.

**Comment by behrang** [comment]
A link to the algorithm is on the homepage of this repository. There you can find the reason for 3000 years limitation.
