### ISSUE TITLE
برگرداندن تاریخ اشتباه

### ISSUE THREAD

**Issue by UKbed990** [jalaali/moment-jalaali#35]
سلام.
ممنون از افزونه بسیار عالیتون.
اما من یه مشکل باهاش دارم.
وقتی یه تاریخ انتخاب میکنم و میخوام نمایشش بدم روز آخر اون ماه رو نشون میده.
مثلا من 14 تیر 92 رو انتخاب میکنم
ولی موقع نمایش تو جدول 31 تیر 92 رو برمیگردونه.
یه سرچ کردم ولی مث اینکه دیگران این مشکلو نداشتن
و جالبه بدونین که تو کنسول وقتی نمایشش میدم این آبجکت رو نشون میده:
_d: Thu May 21 2009 23:59:59 GMT+0430 (Iran Daylight Time)
_f: "YYYY-MM-DD---"
_i: "2009-05-08---"
_isAMomentObject: true
_isUTC: false
_isValid: true
_jDiff: 0

که _i همون تاریخیه که من میخوام
اما _d لحظه ی آخر ماه انتخابی منه که نشونش میده تو جدول
یه دنیا مرسی
moment 2.10.3
moment-jalaali 0.3.8
ممنون میشم راهنماییم کنین

**Comment by behrang** [comment]
Can you provide a code sample?

**Comment by UKbed990** [comment]
yeah.
i'm using MVC5 for server side and angularjs as client side
and using select2 to provide 3 combobox for insert day, month and year.
this is my code:
html:

        <label for="FirstYears" class="control-label col-sm-6 col-sm-push-6">تاریخ شروع سال :</label>
        <div style="display:inline" class="col-sm-6 col-sm-pull-6">
            <input style="width: 100px" ng-model="FirstYear" id="FirstYearInput" />
            <input style="width: 100px" ng-model="FirstMonth" id="FirstMonthInput" />                                    
            <input style="width: 100px" ng-model="FirstDay" id="FirstDayInput" />
        </div> 

and script (angularjs controller):

        $scope.FirstYears = [];
        $scope.FirstMonths = [];
        $scope.FirstDays = [];
        $scope.selectedFirstYear = today.jYear();
        $scope.selectedFirstMonth = today.jMonth() + 1;
        $scope.selectedFirstDay = today.jDate();
        $scope.YearFirstDate = moment($scope.selectedFirstYear + '-' + $scope.selectedFirstMonth + '-' + $scope.selectedFirstDay, 'jYYYY-jM-jD');

        for (var i = 1380; i <= 1400; i++) {
            $scope.FirstYears.push({ id: i, text: i.toString() });
        };

        $scope.FirstMonths = [
                        { id: 1, text: 'فروردین' },
                        { id: 2, text: 'اردیبهشت' },
                        { id: 3, text: 'خرداد' },
                        { id: 4, text: 'تیر' },
                        { id: 5, text: 'مرداد' },
                        { id: 6, text: 'شهریور' },
                        { id: 7, text: 'مهر' },
                        { id: 8, text: 'آبان' },
                        { id: 9, text: 'آذر' },
                        { id: 10, text: 'دی' },
                        { id: 11, text: 'بهمن' },
                        { id: 12, text: 'اسفند' }
        ];

        $scope.generateFirstDays = function () {
            $scope.YearFirstDate = moment($scope.selectedFirstYear + '-' + $scope.selectedFirstMonth + '-' + $scope.selectedFirstDay, 'jYYYY-jM-jD');
            if ($scope.YearFirstDate.isValid()) {
                $scope.endOfSelectedFirstMonth = $scope.YearFirstDate.endOf('jMonth').format('jD');
                $scope.FirstDays.splice(0, 31);
                for (var i = 1; i <= $scope.endOfSelectedFirstMonth; i++) {
                    $scope.FirstDays.push({ id: i, text: i.toString() });
                }
            }
            else {
                $("#FirstDayInput").select2("val", $("#FirstDayInput").val() - 1);
                $scope.selectedFirstDay --;
                $scope.generateFirstDays();
            }
        }
        $scope.generateFirstDays();

        $("#FirstYearInput").select2({
            data: { results: $scope.FirstYears, text: 'text' },
            formatNoMatches: 'ورودی نامعتبر'
        });

        $("#FirstMonthInput").select2({
            data: { results: $scope.FirstMonths, text: 'text' },
            formatNoMatches: 'ورودی نامعتبر'
        });

        $("#FirstDayInput").select2({
            data: { results: $scope.FirstDays, text: 'text' },
            formatNoMatches: 'ورودی نامعتبر'
        });                

        $("#FirstYearInput").on("change", function (e) {
            $scope.selectedFirstYear = e.val;
            $scope.generateFirstDays();
        });

        $("#FirstMonthInput").on("change", function (e) {
            $scope.selectedFirstMonth = e.val;
            $scope.generateFirstDays();
        });

        $("#FirstDayInput").on("change", function (e) {
            $scope.selectedFirstDay = e.val;
            $scope.generateFirstDays();
        });


tnx...

**Comment by UKbed990** [comment]
hi again.
i put my code snippet here.
and i have no more time.
any help????????????
tnx again

**Comment by behrang** [comment]
I'm not familiar with AngularJS. I'm sure you have a bug in your code. What's the purpose of this line:
```
$scope.endOfSelectedFirstMonth = $scope.YearFirstDate.endOf('jMonth').format('jD');
```

Beware that `moment` mutates the instance. So executing the above line will change the `YearFirstDate` instance and set it to last day of month. Maybe your problem is here. You may want to use `.clone()` method to create a copy and then operate on that.

**Comment by UKbed990** [comment]
excellent!
that .clone() stuff worked.
saved my time.
tnx alot
