### ISSUE TITLE
why my code returns wrong date?

### ISSUE THREAD

**Issue by UKbed990** [jalaali/moment-jalaali#36]
سلام.
من از این افزونه ی شما تو کدم استفاده میکنم.
(angular and mvc and web api )
اما یه مشکلی دارم.
تاریخی که ثبت میکنم یک روز زودتر برمیگردونه.
مثلا من در فیلدهای فرمم 23 تیر 94 رو انتخاب میکنم 
و وقتی ثبت رو میزنم 22 تیر 94 رو برمیگردونه.
میشه یه بررسی کنید ببینید مشکل کد من از کجاست؟

این نمونه ی کد اسکریپت من:

        // تاریخ شروع سال        
        
        $scope.FirstYears = [];
        $scope.FirstMonths = [];
        $scope.FirstDays = [];
        $scope.selectedFirstYear = today.jYear();
        $scope.selectedFirstMonth = today.jMonth() + 1;
        $scope.selectedFirstDay = today.jDate();
        $scope.YearFirstDate = moment($scope.selectedFirstYear + '-' + $scope.selectedFirstMonth + '-' + $scope.selectedFirstDay, 'jYYYY-jM-jD');

        for (var i = 1350; i <= 1450; i++) {
            $scope.FirstYears.push({ id: i, text: i.toString() });
        };

        $scope.FirstMonths = [
                        { id: 1, text: 'فروردین' },
                        { id: 2, text: 'اردیبهشت' },
                        { id: 3, text: 'خرداد' },
                        { id: 4, text: 'تیر' },
                        { id: 5, text: 'مرداد' },
                        { id: 6, text: 'شهریور' },
                        { id: 7, text: 'مهر' },
                        { id: 8, text: 'آبان' },
                        { id: 9, text: 'آذر' },
                        { id: 10, text: 'دی' },
                        { id: 11, text: 'بهمن' },
                        { id: 12, text: 'اسفند' }
        ];

        $scope.generateFirstDays = function () {
            $scope.YearFirstDate = moment($scope.selectedFirstYear + '-' + $scope.selectedFirstMonth + '-' + $scope.selectedFirstDay, 'jYYYY-jM-jD');
            if ($scope.YearFirstDate.isValid()) {
                $scope.endOfSelectedFirstMonth = $scope.YearFirstDate.clone().endOf('jMonth').format('jD');
                $scope.FirstDays.splice(0, 31);
                for (var i = 1; i <= $scope.endOfSelectedFirstMonth; i++) {
                    $scope.FirstDays.push({ id: i, text: i.toString() });
                }
            }
            else {
                $("#FirstDayInput").select2("val", $("#FirstDayInput").val() - 1);
                $scope.selectedFirstDay --;
                $scope.generateFirstDays();
            }
        }
        $scope.generateFirstDays();

        $("#FirstYearInput").select2({
            data: { results: $scope.FirstYears, text: 'text' },
            formatNoMatches: 'ورودی نامعتبر'
        });

        $("#FirstMonthInput").select2({
            data: { results: $scope.FirstMonths, text: 'text' },
            formatNoMatches: 'ورودی نامعتبر'
        });

        $("#FirstDayInput").select2({
            data: { results: $scope.FirstDays, text: 'text' },
            formatNoMatches: 'ورودی نامعتبر'
        });                

        $("#FirstYearInput").on("change", function (e) {
            $scope.selectedFirstYear = e.val;
            $scope.generateFirstDays();
        });

        $("#FirstMonthInput").on("change", function (e) {
            $scope.selectedFirstMonth = e.val;
            $scope.generateFirstDays();
        });

        $("#FirstDayInput").on("change", function (e) {
            $scope.selectedFirstDay = e.val;
            $scope.generateFirstDays();
        });
         

        // ثبت 

        $scope.btnSubmit = function (record, index) {
            $scope.newRecord = {
                InvYear: $scope.InvYear,
                YearFirstDate: $scope.YearFirstDate,
                YearEndDate: $scope.YearEndDate
            };

            if ($scope.newRecord.InvYear) {
                $http.post("http://localhost:35621/api/YearApi", $scope.newRecord).success(function (response) {
                    if (response == 0) {
                        $scope.getWholeData();
                    }
                });
            }
        };

**Comment by behrang** [comment]
You have to check it yourself. Please don't create issues with your code samples. Create a small test case that doesn't work, not a whole application. And don't mix different projects like angular in issues. Give a test case using the APIs of this project.
