### ISSUE TITLE
Adding version number to  moment-jalaali.js

### ISSUE THREAD

**Issue by afattahi54** [jalaali/moment-jalaali#37]
Is it possible to add the moment-jalaali version to moment-jalaali.js file ?!

**Comment by behrang** [comment]
Then every time I have to rename it! Use a package manager, like NPM or Bower to control versions.

**Comment by afattahi54** [comment]
Not the file name! I mean a comment block at top of your moment-jalaali.js . This will help to find which versions we are using while looking at the source

**Comment by behrang** [comment]
Version is currently inside `package.json` beside `moment-jalaali.js`. So using those package managers, you would be able to find the version easily.
