### ISSUE TITLE
wrong value of endOf function

### ISSUE THREAD

**Issue by UKbed990** [jalaali/moment-jalaali#40]
سلام
لحظه آخر برخی از سالها رو اشتباه برمیگردونه.
 مثلا تاریخ زیر به درستی 1388/12/29 برگردانده میشه
console.log(moment(1388 + '-' + 1 + '-' + 1, 'jYYYY-jM-jD').endOf('jYear').format('jYYYY/jM/jD'));
ولی بعضی سالها به جای آخر سال ، اول سال بعد رو برمیگردونه مثل سالهای 1378و1389و1395
و1400و1406و1412و1417و....

 مثلا تاریخ زیر به اشتباه 1390/1/1 برگردانده میشه
console.log(moment(1389 + '-' + 1 + '-' + 1, 'jYYYY-jM-jD').endOf('jYear').format('jYYYY/jM/jD'));

**Comment by UKbed990** [comment]
سلام مجدد.
من از افزونه شما استفاده میکنم و خیلی هم راضیم.
این نکاتی هم که میگم واسه بهتر شدن کارتونه.
جسارتا فروردین این سالها (1378و1389و1395و...) فقط روز اول داره.
ینی روز آخرش یک فروردینه.
شاید ماه های دیگر سالهای دیگر هم این مشکلو داشته باشن ولی من فقط به این برخوردم

مثلا:
console.log(moment(1395 + '-' + 1 + '-' + 1, 'jYYYY-jM-jD').endOf('jMonth').format('jD'))

که باید 31 رو برگردونه ولی 1 رو برمیگردونه.
بازم تشکر

**Comment by behrang** [comment]
Issues like this are most of the time because of [Daylight saving time](https://en.wikipedia.org/wiki/Daylight_saving_time). Since in Iran, cocks are changed at `1/1`, moment gets a different date than what you specify. For example, `1388/1/1` may be parsed to `1387/12/30 23:00` which is just an hour earlier, but in another year. Then using `endOf` has a different result.

If you want to be sure, use another day of month in your tests, (like `2`). Also to fix these issues, you can use `moment-timezone` or you can manually add a dummy hour (like 12:00) to your input, and parse with that hour. With this approach, you essentially bypass that special hour in time!

I close this, but if you still think it's an issue, reopen it.

**Comment by UKbed990** [comment]
console.log(moment(1395 + '-' + 1 + '-' + 10 + ' ' + '16:00:00', 'jYYYY-jM-jD HH:mm:ss'));
this is the change that i did, but still have same issue

**Comment by farshadj101** [comment]
Dear @behrang , thanks for your precious work on moment-jalaali. 
using moment-timezone didn't fix my issue, here's my code:

```
moment('1397-01-01', 'jYYYY-jM-jD').tz('Asia/Tehran').endOf('jMonth').format('jYYYY-jM-jD hh:MM') 

//"1397-2-1 12:04"
```

could you please help me fix this without manually adding a dummy hour?
thanks in advance

**Comment by yusefarianpour** [comment]
Dear @farshadj101 , Use `mm` (Hour) instance of `MM` (Month).

This worked for me!
```
var moment = require('moment-jalaali');

moment('1397-01-01', 'jYYYY-jM-jD').endOf('jMonth').format('jYYYY-jM-jD HH:mm');
```

**Comment by farshadj101** [comment]
Dear @yusefarianpour , thanks for your response, but it's not the matter of minutes, I mean look at this code, It's expected to be the end of 1st Jalaali month **(1397-1-31 23:59)**, but it returns **(1397-2-1 00:59)** even though I used time zone.



![image](https://user-images.githubusercontent.com/17934486/42121992-d12e14ea-7c4f-11e8-9a2c-da83c9ed8b65.png)

    "moment-jalaali": "^0.7.4",
    "moment-timezone": "^0.5.21"

**Comment by behrang** [comment]
Dear @farshadj101,
That seems to be the correct behavior, although surprising. That is, for summer time, the first hour of 1397/02/01 is skipped, so the first second of 1397/02/01 starts at 1:00 am, so the end of jMonth is one moment before that, and that is 1397/02/01 00:59:59.

**Comment by farshadj101** [comment]
dear @behrang,
I appreciate your response, this method somehow fixes the problem:
```
endOfJMonth(date) {
const month = date.jMonth(); 
if (month === 0) {
 return moment(date).endOf('jMonth').subtract(1, 'hour');
}

return moment(date).endOf('jMonth');
}
```

It works but I wonder why moment-jalaali is not handling this inside.
 Is there any reason  to not resolve this issue? You said that is a correct behavior, I got confused... isn't it a wrong behavior for endOf function? after all, I expect endOf to return the  end of current month not beginning of next month.

Thanks for your support.
