### ISSUE TITLE
Integrate moment-jalaali.js with bootstrap-datetimepicker

### ISSUE THREAD

**Issue by pournejati** [jalaali/moment-jalaali#42]
I tried to use this moment.js extension with bootstrap-datetimepicker, but when tried to add this library, the page goes into a loop and crashed. How can I resolve this issue and what's the correct way to add "moment.jalaali.js"? This is how I added the package into my page:

    <script src="/Scripts/Libraries/moment.js"></script>
    <script src="/Scripts/Libraries/moment.jalali.js"></script>
    <script src="/Scripts/Plugins/datetimepicker.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            moment().format('jYYYY/jM/jD');
            var m = moment('1366/2/18', 'jYYYY/jM/jD')
            // It shows the following alert:
            alert(m.format('jYYYY/jM/jD [is] YYYY/M/D'));
            $('#birth-date').datetimepicker({
            });
        });
    </script>

**Comment by behrang** [comment]
Try to isolate the problem. Remove the last line for setting datepicker value. See if it still happens. Also you may remove datepicker script.

**Comment by pournejati** [comment]
Thanks for the comment. Apparently this package doesn't override moment.js but extend it. So it doesn't help me to implement Persian calendar with that component.

**Comment by Sajadkiani** [comment]
I have this issue and fixed by:
move bootstrap-datetimepicker.js to above of the moment-jalali.js in html head.

**Comment by NARooshnavand** [comment]
> I tried to use this moment.js extension with bootstrap-datetimepicker, but when tried to add this library, the page goes into a loop and crashed. How can I resolve this issue and what's the correct way to add "moment.jalaali.js"? This is how I added the package into my page:
> 
> ```
> <script src="/Scripts/Libraries/moment.js"></script>
> <script src="/Scripts/Libraries/moment.jalali.js"></script>
> <script src="/Scripts/Plugins/datetimepicker.js"></script>
> 
> <script type="text/javascript">
>     $(document).ready(function () {
>         moment().format('jYYYY/jM/jD');
>         var m = moment('1366/2/18', 'jYYYY/jM/jD')
>         // It shows the following alert:
>         alert(m.format('jYYYY/jM/jD [is] YYYY/M/D'));
>         $('#birth-date').datetimepicker({
>         });
>     });
> </script>
> ```

Hi, I had the same problem. I tried to use others Jalaali calendars libraries. after while I found that this library has pretty written, but the function isSame has a bug. It change the value of inputs moment and this cause issue when you are using bootstrap date time picker.
You mus change isSame with the following 
jMoment.fn.isSame = function (other, units) {
  units = normalizeUnits(units)
  if (units === 'jyear' || units === 'jmonth') {
    var mjthis = toJalaali(this.year(), this.month(), this.date());
    var mjother = toJalaali(other.year(), other.month(), other.date());
    if(units === 'jmonth')
    {
      return (mjthis.jm === mjother.jm);
    }

    return (mjthis.jy===mjother.jy)
    // return moment.fn.isSame.call(this.startOf(units), other.startOf(units))
  }
  return moment.fn.isSame.call(this, other, units)
}

**Comment by NARooshnavand** [comment]
jMoment.fn.isSame = function (other, units) {
  units = normalizeUnits(units)
  if (units === 'jyear' || units === 'jmonth') {
    var mjthis = toJalaali(this.year(), this.month(), this.date());
    var mjother = toJalaali(other.year(), other.month(), other.date());
    if(units === 'jmonth')
    {
      return (mjthis.jm === mjother.jm);
    }

    return (mjthis.jy===mjother.jy)
    // return moment.fn.isSame.call(this.startOf(units), other.startOf(units))
  }
  return moment.fn.isSame.call(this, other, units)
}

**Comment by behrang** [comment]
Please send a pull request. A test case would also help, showing the problem.

**Comment by hamedf62** [comment]
> isSame function in jalaali moment has issue, it change the input moments values, you must replace it with the following
> 
> `jMoment.fn.isSame = function (other, units) { units = normalizeUnits(units) if (units === 'jyear' || units === 'jmonth') { var mjthis = toJalaali(this.year(), this.month(), this.date()); var mjother = toJalaali(other.year(), other.month(), other.date()); if(units === 'jmonth') { return (mjthis.jm === mjother.jm); }
> 
> ```
> return (mjthis.jy===mjother.jy)
> // return moment.fn.isSame.call(this.startOf(units), other.startOf(units))
> ```
> 
> } return moment.fn.isSame.call(this, other, units) }`

completly he/she is right.

isSame with jMonth and jYear change the input undesirable way
