### ISSUE TITLE
angularJS integration

### ISSUE THREAD

**Issue by masious** [jalaali/moment-jalaali#43]
Is there a way that we can integrate this package with amMoment and use it in angular projects?

**Comment by behrang** [comment]
I have no experience with AngularJS. Did you have any problems?

**Comment by masious** [comment]
It seems that .loadPersian() method, is not assigned to the amMoment that is injected in my functions.

**Comment by behrang** [comment]
`loadPersian` is a class method on `MomentJalaali`. It is not an instance method.

**Comment by masious** [comment]
So I guess I can solve the problem with finding a way to inject `MomentJalaali`.
Thanks by the way.
