### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by aliwsd** [jalaali/moment-jalaali#44]
<div>
    <p>سلام ممنون از پلاگین مفیدتون</p>
    <p>من از مومنت جی اس برای <a href="https://github.com/T00rk/bootstrap-material-datetimepicker">دیت پیکر متریال</a> استفاده می کنم.</p>
    <p> ولی وقتی </p>
    <p> moment-jalaali.js </p>
    <p> به صفحه اضافه می کنم دیت پیکر کار نمیکنه و خطای زیر رو توی کنسول مرورگر میاره</p>
    <p>Uncaught TypeError: string.indexOf is not a function moment-jalaali.js:705</p>
    <p> در ضمن اینم بگم که این دیت پیکر با همین سایت مومنت جی اس کار میکنه </p>
    <p> .از سازنده ی دیت پیکر پرسیدم گفت خطا از مومنت جلالی جی اس هست و باید از شما بپرسم </p>
    <p> ممنون </p>
    <a href="http://uupload.ir/files/suqd_myproblem.jpg">اسکرین شات مشکل</a>
</div>

**Comment by behrang** [comment]
Can you make a JSFiddle? I might be able to debug it online.

**Comment by aliwsd** [comment]
No, I Don't know how work it, I Shared with you on Google Drive
thanks a lot.

**Comment by aliwsd** [comment]
No, I Don't know how work it, I Shared with you on Google Drive
thanks a lot.

**Comment by aliwsd** [comment]
No, I Don't know how work it, I Shared with you on Google Drive
thanks a lot.

**Comment by behrang** [comment]
That bug is fixed. However, I don't think you would be able to use that date picker with current design of moment-jalaali.

I'll try to redesign moment-jalaali to make it more compatible with date pickers. You may subscribe to issued #31.

**Comment by aliwsd** [comment]
Thanks a lot, My Problem almost Solved, I have got a little problem, first week days Min from right is ' I ' Instead of ' ی '.  ScreenShot: 
![mp](https://cloud.githubusercontent.com/assets/13856958/9682292/9003da4c-531a-11e5-952f-1615d860303c.jpg)

how can i make true it?
I Checked Js file, it is true: ```weekdaysMin: 'ج_ش_ی_د_س_چ_پ'.split('_')```

**Comment by aliwsd** [comment]
Ok Thanks.
