### ISSUE TITLE
استفاده در یک پروژه انگورال جی اس

### ISSUE THREAD

**Issue by mrbf** [jalaali/moment-jalaali#45]
با سلام
من در پروژه ام از ابزار 
gulp
برای یکپارچه سازی فایلهای جاوا اسکریپت استفاده می کنم. 
ولی وقتی پروژه را به سرور منتقل می کنم خطایی می دهد که متوجه شدم باید عبارت 
use strict
را در کتابخانه شما اضافه کنم. ولی بعد خطا می دهد که
Uncaught TypeError: Cannot set property 'moment' of undefined
روی خط ۱۱۴۰ برنامه.
اگر ۶ خط آخر برنامه را حذف کنم دیگر خطا نمی دهد ولی مسلما برنامه درست کار نمی کند.
در صورت امکان راهنمایی بفرمایید بعد از اضافه کردن 
use strict
چه تغییر دیگری باید در کتابخانه شما بدهم.
جهت اطلاع قبل از یکپارچه سازی برنامه بخوبی کار می کند.

با تشکر

**Comment by behrang** [comment]
This library does not need `use strict`. It seems that one of your build tasks, require it. It must be some linter that needs it. You should not lint `moment-jalaali`.

**Comment by mrbf** [comment]
با سلام

با تبدیل آخرین خط برنامه از
})()
به 
}).call(this);
مشکل من حل شد.
