### ISSUE TITLE
‫چگونگی استفاده از moment-jalaali در برنامه‌ای دیگر؟

### ISSUE THREAD

**Issue by perpi** [jalaali/moment-jalaali#46]
سلام
‫ری-اکشن-کامرس یک نرم افزار فروشگاهی جدیده که ‫توسعه‌دهنده‌هاش از Moment.js برای تقویمش استفاده کردن، اما تجربه چندانی با تقویم زبان‌های دیگه ندارن. اگر ممکنه بهشون مشورت بدین که این امکان رو اضافه کنن که بشه این تقویم جلالی رو هم بسادگی در برنامه شون فعال کرد.
‫تیمشون روی لینک زیر معمولا فعال هستند:
https://gitter.im/reactioncommerce/reaction

‫‫و برنامه شون هم به صورت متن باز روی گیتهاب در حال توسعه است:
https://github.com/reactioncommerce/reaction-core
https://github.com/reactioncommerce/reaction

‫نرم‌افزار ‫Reaction طراحی و قابلیت های مدرنی داره و آماده شده نسخه بتای خودش رو منتشر کنه.  ‫این نرم‌افزار با Meteor نوشته شده و از RTL هم پشتیبانی می‌کنه. تا حالا به عربی و عبری هم ترجمه شده.

**Comment by behrang** [comment]
For easier integration, this needs a redesign in `moment-jalaali`. After redesign, integration will be really easy. I say you better wait for the redesign by following #31.

**Comment by sajjadnasiribrn** [comment]
ط
