### ISSUE TITLE
How do i display farsi characters 

### ISSUE THREAD

**Issue by tomvolek** [jalaali/moment-jalaali#47]
HI , Great plugin .   Hww do I use moment.loadPersian()  to display result of moment(new Date()).format('jYYYY/jM/jD');  in farsi ?  

Thanks

**Comment by behrang** [comment]
`moment-jalaali` does not replace numeric digits with their Persian equivalents. If you need that, use `moment`'s localization which has this feature.

But if you want to display month names in Persian, `jM` in your format string should be changed to `jMMMM`. This way you will get month name (for example "Mehr"), and if you want to get Persian month name, you can use `moment.loadPersian()` statement, before using the format in another statement. This way you'll get "مهر".

**Comment by tomvolek** [comment]
Thanks Behrang.  This is what I have : 
 if (TAPi18n.getLanguage() == 'en') {
            return moment(new Date()).format("dddd, MMMM Do YYYY");
        }
        else if (TAPi18n.getLanguage() == 'fa') {
            moment.loadPersian();
            return moment(new Date()).format('jYYYY/jMMM/jD');
        }

And this is the output I get :  	1394/مهر/26 

I know this has nothing to do with your moment-jalaali plugin, but I assume somewhere I need to define the numbers to get translated to .  Where would that be ? 

Regards

**Comment by behrang** [comment]
Read here: http://momentjs.com/docs/#/i18n/changing-locale/ and use "fa-IR".

**Comment by tomvolek** [comment]
interesting , the latest moment.js has a local for Persian . https://github.com/moment/moment/blob/develop/locale/fa.js

However statement moment.locale('fa');   doesn't load it as the documentation shows  in your above link.  
I am wondering If I have to define the moment.local('fa', {.....} );   explicitly in my javascript code.

**Comment by behrang** [comment]
You need to add fa locale to your project. Read more there.

**Comment by tomvolek** [comment]
I Behrang.   You helped me with a moments question few months back.    I live in San Francisco , 

Man allan omadam Tehran.  Einja meteor developer hast ?  Vakht Dari telephoni sohbat koneem ? 

Mamnoon mesham

Hamid

**Comment by behrang** [comment]
Yes you can call me.

**Comment by tomvolek** [comment]
What is your phone number ?

**Comment by behrang** [comment]
Send me an email. My email is on my profile page.
