### ISSUE TITLE
مشکل در تغییر ماه

### ISSUE THREAD

**Issue by Gholizadeh-Mostafa** [jalaali/moment-jalaali#48]
تغیر تاریخ مشکل دارد
 برای مثال :اگراز تاریخ 1394/12/1بخواهیم به ماه بعد تبدیل کنیم به جای تبدیل به 1395/1/1 ، به تاریخ 1394/12/29 تبدیل میشود .  !!!
چرا؟؟

**Comment by behrang** [comment]
That's because of daylight saving time. This also happens on Shahrivar 30th.

You can set hour in your input date, and then add 1 month. For example, use `1394/12/1 12:00` and then add 1 month.
