### ISSUE TITLE
مشکل در محاسبه روزها

### ISSUE THREAD

**Issue by HamidDarash** [jalaali/moment-jalaali#49]
سلام برنامه شما دارای مشکل است

var sample1 = moment('1360/5/26', 'jYYYY/jM/jD HH:mm');
                    var sample2 = moment('1394/9/24 14:59', 'jYYYY/jM/jD HH:mm').format('YYYY-M-D HH:mm:ss'); // 2013-8-25 16:40:00

                    var sample3 = moment('2015-12-13 14:00:00', 'YYYY-M-D HH:mm:ss').endOf('jMonth').format('jYYYY/jM/jD HH:mm:ss'); // 1392/6/31 23:59:59
                    console.log("sample2 : " + sample2);

------------------------------------------------------------------------------------------------------------------------
Output Console:

sample2 : 2015-12-15 14:59:00
2 روز بیشتر نشون میده
در تبدیل به شمسی 8 روز اختلاف هست

**Comment by behrang** [comment]
امروز ۲۲ آذر است برابر با ۱۳ دسامبر و ۲۴ آذر همان ۱۵ دسامبر است.
بیشتر دقت کنید.

**Comment by HamidDarash** [comment]
مهندس من الان امتحان کردم

time zone:3.30 tehran

var s2 =  moment('2015-12-13 16:40:00', 'YYYY-M-D HH:mm:ss').endOf('jMonth').format('jYYYY/jM/jD HH:mm:ss');  

Output:
1394/9/30 23:59:59
 مشکل کار من کجاست لطفا بهم بگید
ممنون

**Comment by behrang** [comment]
.endOf('jMonth')

پايان ماه جلالي را بر ميگرداند. 




اگر پايان ماه ميلادي را ميخواهيد


.endOf('month')


را به كار بريد.

**Comment by HamidDarash** [comment]
بسیار سپاس گذارم مهندس
