### ISSUE TITLE
build directory is not up-to-date

### ISSUE THREAD

**Issue by alirezamirian** [jalaali/moment-jalaali#50]
I encountered an error while I was concatenating my libs (one of them being moment-jalali), and it turned out that the **missing semicolon** at the end of the file was the issue. I came here to fix it but it seems it's already fixed  in #28 . However the content of **build** directory doesn't seem to be generated from last versions of builder because it lacks that semicolon. 
It seems a bit strange cause the last update date is 4 months ago for **build** directory and 8 months ago for **builder**! Maybe that was a manual update of build directory.

**Comment by behrang** [comment]
Thanks, it is fixed now.
