### ISSUE TITLE
Validate date with large year

### ISSUE THREAD

**Issue by afattahi54** [jalaali/moment-jalaali#53]
When I call `moment('4444/12/12', 'jYYYY/jMM/jDD').isValid()` I did not get false as return, instead I see  `Error: Invalid Jalaali year 4444` in the console log.

Shouldn't the invalid year cause the validate to return false?!

**Comment by behrang** [comment]
Yes, it is better, but it is currently really hard. The underlying library, `jalaali-js` has a function called `isValidJalaaliDate` that checks the validity of a date. But with current implementation of `moment-jalaali` it is hard, as you can pass different configurations for input string.

Currently, moment constructor throws that exception that you said and you have to catch.

**Comment by alitaheri** [comment]
I'm closing this as it's not worth exploring the workaround is easy enough ( try/catch block ). PRs are always welcome 😁
