### ISSUE TITLE
اعداد فارسی

### ISSUE THREAD

**Issue by amastaneh** [jalaali/moment-jalaali#56]
متاسفانه خروجی شامل اعداد با کدهای انگلیسی است و مناسب است که به کدهای فارسی تبدیل شود

**راهکارهای دیگر
**استفاده از لوکال-مومنت به جای مومنت علاوه بر افزایش حجم سربار باعث نمایش وارنینگ می شود

**شیوه اصلاح
**مشابه لوکال-مومنت می توان با استفاده از دو متد زیر اعداد را قبل از ورود تبدیل به انگلیسی کرد (برای پردازش های داخلی) و قبل از خروج با کدهای فارسی جایگزین نمود.
`preparse`و `postformat`

**Comment by behrang** [comment]
می توانید از زبان فارسی در خود
`moment`
استفاده کنید که این ویژگی را دارد.

**Comment by amastaneh** [comment]
&#x202b;همانگونه که توضیح داده شده است، استفاده از moment-with-locales به جای moment.js برای استفاده از امکانات فارسی معایب زیر را به همراه دارد

1. &#x202b;warning (دلیل اصلی)
![image](https://cloud.githubusercontent.com/assets/6195199/14410121/d7b737ee-ff3b-11e5-81e6-2fbf8be31b0c.png)

2. &#x202b;سرباره 52 کیلوبایتی moment-with-locales در حالی که فقط دو متد  کوتاه `preparse` و `postformat` می تواند این امکان را به سادگی فراهم سازد

3. &#x202b;عدم تطبیق پذیری ورودی با کاراکترهای فارسی

**Comment by behrang** [comment]
1. moment-with-locales
همه ی زبان ها را به همراه دارد و برای همین هم حجم آن بالاست. می توانید تنها زبان فارسی را بگیرید و به کار برید که حجم بسیار ناچیزی دارد.

2. من با افزودن دو متد گفته شده مخالف هستم. به این دلیل که با افزودن این دو متد، تنها تاریخ ها با رقم های فارسی نمایش داده می شوند. برای به کار گیری رقم های فارسی در دیگر بخش های برنامه، باز هم به یک کتابخانه ای که این کار را انجام دهد نیاز خواهید داشت. وقتی آن کتابخانه را به کار برید، می توانید آن را برای رقم های تاریخ نیز به کار برید. از اینرو این ویژگی در این کتابخانه پیاده سازی نشده است و ویژگی های فارسی که گذاشته شده اند،‌بدون آن هستند.

3. هشداری که گرفته شده، از 
moment-with-locales
است. احتمالا به این دلیل که پس از
moment-jalaali
آورده شده است.
moment-jalaali
را پس از آن قرار دهید و اگر همچنان هشدار میگرفتید، بگویید تا درست شود.

**Comment by amastaneh** [comment]
جناب بهرنگ با تشکر از بررسی
1. در سایت momentjs.com نسخه مجزا برای هر فرهنگ نیست و پکیج nuget آن نیز نسخه های مجزا برای هر فرهنگ ندارد
2. ما این دو رو اضافه کردیم و هم تاریخ و هم زمان و هم نوشته های مرتبط فارسی شد
2. کتابخانه های اضافه سرباره ی همراه (حجم و پردازش) دارند
3. خیر به جای مومنت اصلی اضافه شده است. این هشدار نیز در آپگرید نسخه جدید به مومنت اضافه شده است

نکات فنی توضیح داده شده است و سلیقه شما هم می تواند بر روی تصمیم تاثیر بگذارد. 
به هر صورت، ارائه خروجی یا دریافت ورودی منطبق با کاراکترهای ملی و بومی مزید امتنان است.

**Comment by behrang** [comment]
* فایل فارسی در این مسیر است:
https://github.com/moment/moment/blob/develop/locale/fa.js

* کتابخانه ی اضافه ای نیست اگر تنها زبان فارسی را بگیرید.

* آیا
loadPersian
را فراخوانی کرده اید؟ اگر اینطور است، کافیست آن را فراخوانی نکنید. این تابع برای زمانی است که از
locale
های مومنت استفاده نمی کنید. اگر استفاده می کنید دیگر آن را فراخوانی نکنید.
