### ISSUE TITLE
problem with first day of week in fullcalendar

### ISSUE THREAD

**Issue by mmnaderi** [jalaali/moment-jalaali#58]
سلام.
بنده از
github.com/ehsandanesh/fullcalendar
استفاده میکنم که این پروژه از
github.com/ehsandanesh/moment-jalaali
استفاده میکنه که یه کمی با مال این پکیج فرق داره.

مشکل این جاست که من چه از این پکیج و چه از پکیج مذکور استفاده کنم هرکدام مشکلی دارند که دیگری ندارد.
مشکلی که این پکیج دارد این است که روز شروع هفته را همین روز فعلی قرار میدهد در صورتی که طبق مشخص کردن روز شروع هفته باید از شنبه شروع کند.
برای حل کردن این مشکل چه توان کرد؟

![screenshot](https://cloud.githubusercontent.com/assets/2914924/16025000/1e29cf86-31da-11e6-8da1-86a7eeea4e2e.png)

**Comment by behrang** [comment]
مشکل باید در نمایش تقویم باشد. چون
moment-jalaali
کاری با روز هفته ندارد. پیشنهاد میکنم هر دو پروژه ی
moment-jalaali
را آزمایش کنید و ببینید که روز هفته را درست برمی گردانند یا خیر.
