### ISSUE TITLE
problem in moment .now function

### ISSUE THREAD

**Issue by sinoohe** [jalaali/moment-jalaali#64]
Hi,
there is a problem with Moment.now function when using moment-jalaali,
Moment.now is never called, I read the source code, you call the original moment function from makeMoment function, it should work find but I don't understand why .now is never called!

I prepared jsfiddle : http://jsfiddle.net/k1sa87t6/1/
my code starts from line 1157

**Comment by behrang** [comment]
I don't understand the question. This project only adds some helper methods for Jalaali conversion and it does not mess with `moment.now`.

**Comment by sinoohe** [comment]
you can change the source time by overriding moment.now function, but when I use moment-jalaali library moment.now is never called, it seems that there is something wrong with moment-jalaali,
I have read the moment-jalaali source code, It's very strange for me why it happens, because you haven't override much functions.

you can see the code sample from jsfiddle, the moment.now function is never called, but if you remove moment-jalaali source code, it works very fine!!

**Comment by sinoohe** [comment]
This is a sample code in nodejs:
```
var moment=require('moment-jalaali');
moment.now=function(){
  console.log('this is not called');
  return +Date.now();
};
console.log(moment().toDate());

```

**Comment by behrang** [comment]
Ok, I got it. Try overriding `moment.now` after requiring `moment` but before requiring `moment-jalaali`.

**Comment by behrang** [comment]
These lines copy `moment` properties to `moment-jalaali`:
```js
extend(jMoment, moment)
jMoment.fn = objectCreate(moment.fn)
```
