### ISSUE TITLE
عنوان لاتین ماه‌های شمسی

### ISSUE THREAD

**Issue by ahmadazimi** [jalaali/moment-jalaali#65]
سلام و وقت بخیر،

یکی از دوستان توسعه‌دهنده از این کتابخانه در پروژه‌ی فول-کلندر جلالی استفاده کرده است.
اما عنوان ماه‌ها در بالای تقویم بصورت فینگلیش نمایش داده میشه. مانند
Amordad

البته فول-کلندر امکان تغییر فرمت رو داره و میشه از اون برای تغییر فرمت استفاده کرد. اما من هر چه تلاش کردم به نتیجه نرسیدم. قاعدتاً چنانچه از فرمت زیر استفاده کنم باید نام ماه‌های فارسی نمایش داده بشن مانند شهریور. اما اینگونه نیست. من از فرمت‌های زیر استفاده کردم:
JM, JMM, JMM

کدهای شما رو هم دیدم. شما ترجمه‌های صحیح رو گذاشتید داخل کد اما هنگامی که کتابخانه مومنت قراره از فرمت شما استفاده کنه، مقدار لاتین و فینگلیش ماه رو برمی‌گردونید.

لطفاً راهنمایی کنید. ممنونم

**Comment by ahmadazimi** [comment]
مساله‌ی دیگه‌ای هم که من مشاهده کردم این بود که به عنوان مثال وقتی با فاصله از دو عبارت مانند زیر استفاده می‌کنید برای فرمت مومنت، به شکل عجیبی همه چیز بهم میریزه:
` JMMM JYYYY`

خروجی این فرمت بصورت زیره:
`Amordaad J — J۱۳۹۵`

خب در صورتی که از استاندارد هم استفاده کنم یعنی:
`MMMM YYYY`

خروجی به این صورت خواهد بود:
`Amordaad ۱۳۹۵`

**Comment by behrang** [comment]
About your first problem, calendar system and locale are two different things. To change locale, you have to call `#loadPersian()` method.

About the second problem, it looks that another library, is substituting moment format tokens with jalaali compatible ones. So when using that library, you have to drop `j` prefix.

**Comment by ahmadazimi** [comment]
Hi Behrang,

calling #loadPersian() throw the following exception when using fromNow() method:

`moment.js:3104 Uncaught TypeError: Cannot read property 'humanize' of undefined`

Do you have any idea about it?

**Comment by behrang** [comment]
Thanks for the report. Fixed in `0.5.1`.

**Comment by ahmadazimi** [comment]
Thank you @behrang, It's working fine.

**Comment by behrang** [comment]
You're welcome.

**Comment by mamos98** [comment]
@ahmadazimi 
Hey,
I have the exact same issue expressed by Ahmad!
May I ask which fullcalendar jalaali are you using!? A link to the repository would be great.

**Comment by ahmadazimi** [comment]
@mamos98 
Hi,
This is what I have used:
[https://github.com/ehsandanesh/fullcalendar](https://github.com/ehsandanesh/fullcalendar)

**Comment by mamos98** [comment]
@ahmadazimi 
Hey there,
I did exactly the same thing to the latest version of full calendar v3.1.0!
I'm gaining the Jalaali Functionality, but the name of the months in the title is still somehow shown in Finglish!

For example "Dey" is shown instead of "دی". I was curious how should I fix this and since you mentioned that you've fixed this specific error I wanted to know how did you do it!?

Maybe you could share it with me or contribute to the fork I've made from the latest version of full calendar!

[My Forked Repository](https://github.com/mamos98/fullcalendar)
