### ISSUE TITLE
هنگ سایت

### ISSUE THREAD

**Issue by nbastreet** [jalaali/moment-jalaali#66]
سلام.
وقتی فایل
moment-jallai.js
فراخوانی میشه سایت و در کل مرورگر برای چند دقیقه هنگ میکنه و با هر بار کلیک روی فیلد دارای تقویم این اتفاق می افته و عملا قابل استفاده نیست!
چه دلیلی می تونه داشته باشه این موضوع؟
باتشکر

**Comment by behrang** [comment]
چه کتابخانه ی دیگری را به کار میبرید؟

شاید به دلیل ناسازگاری میان این کتابخانه و یکی از کتابخانه های شما باشد.

**Comment by nbastreet** [comment]
ببخشید من مبتدی هستم و فکر می کنم این سوال خیلی سوال پیش افتاده ای باشه اما میشه بفرمایید استفاده از این کتابخانه به زبان برنامه نویسی سایت مربوط میشه یا خیر؟
در واقع من دارم این کتابخانه رو در یک قالب وردپرس فراخوانی می کنم، این مشکلی نداره؟
البته از
moment.js
استفاده شده است در خود قالب
اگر زبان برنامه نویسی تفاوتی ندارد تا سایر فایل ها جی کوئری موجود در قالب رو هم عرض کنم خدمتتون

**Comment by nbastreet** [comment]
از این کتابخانه هم در قالب استفاده شده است که فکر می کنم تداخل با این کتابخانه هست!
https://github.com/Eonasdan/bootstrap-datetimepicker

**Comment by behrang** [comment]
شاید همین کتابخانه مشکل باشد و برای کار با
`moment-jalaali`
مناسب نباشد. بهتر است از همان پروژه پیگیری کنید.

**Comment by per3ian** [comment]
با سلام

بنده هم این مشکل رو دارم!
و خیلی برام مهم هست که از این لایبرری استفاده کنم :
https://github.com/Eonasdan/bootstrap-datetimepicker

خود این لایبرری داره momentjs رو پیشنهاد میده. اما فقط فارسی می کنه و جلالی نمیکنه تقویم رو. 
فکر می کنم این خطا رو شما باید از سمت لایبرری خودتون بررسی بفرمائید.

ممنون
