### ISSUE TITLE
[On Hold] Typescript 2 typings

### ISSUE THREAD

**Issue by alitaheri** [jalaali/moment-jalaali#67]
Please have a look at this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11024) and see if all the extended API is included. Please note that it will only be usable with typescript@next.

**Comment by behrang** [comment]
I don't know type script, and your PR looks great. Thanks.

**Comment by behrang** [comment]
Should we add anything to this project's Readme?

**Comment by alitaheri** [comment]
> Should we add anything to this project's Readme?

It would be appreciated, but I suggest we wait for typescript 2 to be released. Please keep this issue open for now until ts 2 is released. thanks :+1:

**Comment by behrang** [comment]
Allright.

**Comment by alitaheri** [comment]
They are added and are in production:

`npm install @types/moment-jalaali`
