### ISSUE TITLE
Pass extra options to moment.loadPersian

### ISSUE THREAD

**Issue by ahmadazimi** [jalaali/moment-jalaali#69]
Is there any chance for developers to pass extra parameters to `moment.loadPersian` method?

I think developers should have ability to override persian locale parameters, like this:

```
moment.loadPersian({
  longDateFormat: {
    LLL: 'jD jMMMM jYYYY [ساعت] LT',
    LLLL: 'dddd، jD jMMMM jYYYY [ساعت] LT'
  }
});
```

Currently I'm using this way:

```
moment.loadPersian();

moment.updateLocale('fa', {
    longDateFormat: {
        LLL: 'jD jMMMM jYYYY [ساعت] LT',
        LLLL: 'dddd، jD jMMMM jYYYY [ساعت] LT'
    }
});
```

**Comment by behrang** [comment]
Actually it is very easy. If you are not happy with your current solution, I encourage you to provide a PR.

**Comment by alitaheri** [comment]
Not worth exploring as the workaround is easy enough. a PR is always welcome though 😉
