### ISSUE TITLE
سنجش کیفیت کد

### ISSUE THREAD

**Issue by aaghamohammadi** [jalaali/moment-jalaali#72]
سلام
اخیرا با ابزاری به نام
codacy.com
آشنا شدم که کیفیت کد را بر حسب شاخص‌های متفاوتی ارزیابی میکند. برای مخزن پایتون گاهشمار جلالی انجام دادم. با
اجازه برای مخزن جاوا اسکریپت هم اضافه کردم. کیفیت کد نمره ی 
A
دریافت کرد که خیلی خوب است. البته ۷ تا 
clone
هم در کد تشخیص داده شد.
از طریق 
(https://www.codacy.com/app/al-aghamohammadi/moment-jalaali/dashboard)
میتوانید به ارزیابی دسترسی داشته باشید.
برای مشاهده مشکلات کیفیت کد به قسمت فایل‌ها میتوانید بروید.

با احترام
ع.آقامحمدی

**Comment by behrang** [comment]
درود
مشکلات گفته شده را در زمان مناسبی درست خواهم کرد.
سپاس
