### ISSUE TITLE
loadPersian() doese not change months and years correctly

### ISSUE THREAD

**Issue by Yarandi** [jalaali/moment-jalaali#73]
i'm using your useful plugin beside [daterangepicker](http://www.daterangepicker.com/) . 
but i have an issue

according to your documents when i use `moment.loadPersian(); ` the calender doese not change Months name to the jalali Months . 

it return for example : 'ژانویه'  and the years still shows in Gregorian years
what should i do for change these months to for example 'آذر' ?

Thanks in advance

**Comment by behrang** [comment]
You have to use Jalaali tokens (`jYYYY`, `jM`, `jMM`, `jD`, ...) for formatting. For example, `jMMMM` displays Jalaali month but `MMMM` displays Gregorian month.

**Comment by Yarandi** [comment]
Could you give me an example please?
Where should i use Jalaali tokens (jYYYY, jM, jMM, jD, ...) as format ?

This is my loading structure:

```
<!-- Include Required Prerequisites -->
<script type="text/javascript" src="{!! asset('assets/jquery-v2.0.3/jquery.js') !!}"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />

<script type="text/javascript" src="{!! asset('assets/moment.js') !!}"></script>
<script type="text/javascript" src="{!! asset('assets/moment-jalaali.js') !!}"></script>
<script> moment.loadPersian();</script>


<!-- Include Date Range Picker -->
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

<input type="text" name="daterange" value="01/01/2015 - 01/31/2015" />
<script type="text/javascript">
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            locale: {
                format: 'jYYYY-jM-jD'
            },
        });
        //alert(moment().format('jYYYY/jM/jD'));
    });
</script>
```

![screenshot_4](https://cloud.githubusercontent.com/assets/1158575/21146023/8dc1ac22-c165-11e6-89fa-45f596ec7090.png)

**Comment by behrang** [comment]
Date range picker, internally uses moment, and moment-jalaali does not change moment's functions. Instead it adds some more helpers. As a result, just including moment-jalaali does not change date range picker. For it to display and pick Jalaali dates, date range picker has to change a lot to be able to display and pick Jalaali dates. In #31 we tried to make it easier, but we failed.
