### ISSUE TITLE
how to call isValidJalaaliDate in typescript?

### ISSUE THREAD

**Issue by deadmann** [jalaali/moment-jalaali#74]
I'm using type script, i understand that i can't use isValid for persian datetimes, so after some search i found another topic right here, that pointed that i need to call isValidJalaaliDate. after looking inside the typing script of jalali date, i found that it used require. that's where i don't know how to import. :|

**Comment by behrang** [comment]
I don't have any experience with TypeScript.

@alitaheri Can you help us here?

**Comment by alitaheri** [comment]
@deadmann If you're using typescript version > 2.0 then you can install the typings:

`npm install @types/moment-jalaali`

However, `isValidJalaaliDate` is not in `moment-jalaali` it's located in `jalaali-js`. You can follow in my footsteps and make a PR in DefinitelyTyped repo like [I did](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11024) and add the API for the `jalaali-js` repo so that the following code would work:

```ts
import { isValidJalaaliDate } from 'jalaali-js';
isValidJalaaliDate(1395, 12, 30); // true
```

**Comment by deadmann** [comment]
i did this, but i didn't knew `import { isValidJalaaliDate } from 'jalaali-js';`...
so i need to find the code in that post... there are lot of change sets, but is there actual code that i should use? or u mean i should use this typings "jalaali-js" instead of this "moment-jalaali"?

**Comment by behrang** [comment]
@alitaheri Can you please help here?

**Comment by alitaheri** [comment]
@deadmann you should install `jalaali-js` separately.

`npm install --save jalaali-js`

you can use it like this:

```ts
import { isValidJalaaliDate } from 'jalaali-js';
isValidJalaaliDate(1395, 12, 30); // true
```

And if you see typescript complaining you can ( probably because of having `noImplicitAny` on ) you can do this:

```js

const { isValidJalaaliDate } = require('jalaali-js');
isValidJalaaliDate(1395, 12, 30); // true
```

**Comment by deadmann** [comment]
i'm tired of this... i send a date time, and i get something else, if i send the same thing back, it will fail and is three day off
if i some how hack and hardcode the date i desire, then the timezone fail although it show same date in server... if i send .... i tried many ways.... i start hating dates, and i gonna replace it all with string soon, yeah i loss comparision ability, but man, date is s***

**Comment by alitaheri** [comment]
@deadmann I've published the types for my use case. As soon as [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13702) is merged you can use typescript too:

`npm install @types/jalaali-js`

then:
```ts
import { isValidJalaaliDate } from 'jalaali-js';
isValidJalaaliDate(1395, 12, 30); // true
```

cc @behrang

**Comment by behrang** [comment]
Great. Thanks.
