### ISSUE TITLE
Integrate with Endosan's bootstrap datetimepicker

### ISSUE THREAD

**Issue by Mo3ta9em93** [jalaali/moment-jalaali#75]
Please take a look at Eonasdan's bootstrap datetimepicker [here](https://github.com/Eonasdan/bootstrap-datetimepicker)
it uses moment with locales
is there any way i can implement moment-jalaali with it
the page freezes whenever i call the datepicker
thank you very much

**Comment by behrang** [comment]
Unfortunately, this is not easy. Jalaali is not a locale, it is a calendar system and in moment-jalaali you can use both calendar system concurrently. As a result, that date picker needs substantial change to work with moment-jalaali. In #31 we tried to make this easier but we failed. I encourage you to help here.

**Comment by fingerpich** [comment]
You could use this [fork](https://github.com/fingerpich/jalali-moment) and following code to use Jalali system instead of Gregorian

```js
moment.useJalaliSystemPrimarily();
moment().format('YYYY/MMMM/D'); // 1396/Tir/4
```

**Comment by alitaheri** [comment]
Thanks @fingerpich 👍

**Comment by heidarymr** [comment]
> You could use this [fork](https://github.com/fingerpich/jalali-moment) and following code to use Jalali system instead of Gregorian
> 
> ```js
> moment.useJalaliSystemPrimarily();
> moment().format('YYYY/MMMM/D'); // 1396/Tir/4
> ```

not work!
