### ISSUE TITLE
TimeStamp conversion

### ISSUE THREAD

**Issue by blacksrc** [jalaali/moment-jalaali#76]
I couldn't find any document to convert timestamp to persian date. for instance:
`moment(1456689556, 'jYYYY/jM/jD HH:mm') // 2013-8-25 16:40:00`
 is it possible ?

**Comment by behrang** [comment]
```js
moment(1456689556000).format('jYYYY/jM/jD HH:mm')
moment(1483164017100).format('jYYYY/jM/jD HH:mm')
```

**Comment by alitaheri** [comment]
@blacksrc This library is an extension of [moment.js](http://momentjs.com/) I suggest you read their documentation thoroughly before using this extension library.
