### ISSUE TITLE
problem with the new version of moment

### ISSUE THREAD

**Issue by azerafati** [jalaali/moment-jalaali#77]
After I updated my main moment library, this function is not working as expected
in README file you have 
`moment('1981 5 17', 'YYYY jM D').format('YYYY/MM/DD') // 1981/07/17`

But now it's returning `// 1981/05/17`

**Comment by behrang** [comment]
Tested with moment@2.17.1 and it produced expected result.

**Comment by azerafati** [comment]
@behrang Well, I tested again and prepared a jsfiddle for you! Maybe I've forgotten how to use this library. please take a look at the console.

https://jsfiddle.net/1Lfy7o6e/

**Comment by behrang** [comment]
Seems to be the problem caused by Iran's filtering of internet 😒

https traffic from `raw.githubusercontent.com` is filtered and so the script was not loaded and moment is not overridden. Unfiltering the internet fixes it!
