### ISSUE TITLE
jmonth اشتباه بر میگرده

### ISSUE THREAD

**Issue by farshadjahanmanesh** [jalaali/moment-jalaali#78]
سلام وقت بخیر
توی سمپلی که گذاشتین هم نگاه کنین
1360/5/26
m.jYear() // 1360
**m.jMonth() // 4**
m.jDate() // 26
درصورتیکه باید ۵ باشه

**Comment by behrang** [comment]
در 
moment
ماه ها از صفر آغاز می شوند.
