### ISSUE TITLE
Deprecation Notice - moment.updateLocale

### ISSUE THREAD

**Issue by azerafati** [jalaali/moment-jalaali#80]
using the moment 2.17.1 I get a warning, 
`Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.`

Which is triggered at , [this line here](https://github.com/jalaali/moment-jalaali/blob/master/build/moment-jalaali.js#L1059). For the next version this needs to be looked at.

**Comment by behrang** [comment]
Fixed in release `0.6.0`.

**Comment by AliChraghi** [comment]
درست نشده :(
