### ISSUE TITLE
how show persian full date alephbet?

### ISSUE THREAD

**Issue by manvfx** [jalaali/moment-jalaali#83]
من وقتی دستور زیر را استفاده میکنم
moment().format('[امروز] dddd jD jMMMM jYYYY')
بصورت انگلیسی نمایش میده! فارسی نمیشه!

![01](https://cloud.githubusercontent.com/assets/6747872/23132163/f781d872-f7a1-11e6-9aa9-dde679e43abd.jpg)

بجای esfand خوده کلمه اسفند را چاپ کنه

**Comment by behrang** [comment]
[Read the documentation](https://github.com/jalaali/moment-jalaali).
