### ISSUE TITLE
خطا: Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by smahdi** [jalaali/moment-jalaali#87]
سلام و خدا قوت
سال نو مبارک
من داخل مرورگر کروم تست کردم، هردو فایل ذکر شده را اضافه کردم ولی خروجی به شکل:
j2017/j3/j28
نمایش داده میشه!
در کنسول هم خطای:
_Uncaught ReferenceError: moment is not defined
    at moment-jalaali.js:30
    at moment-jalaali.js:1157_
همواره شاد و پیروز در پناه حق

**Comment by smahdi** [comment]
من توی انگولار دارم ازش استفاده میکنم و به صورت 
LazyLoading 
بارگزاری میکردم فایل هام را و به خطا می خوردم
مستقیم که وارد کردم درست شد.
!?حال چرا نمیدونم
;-) مچکرم

**Comment by alitaheri** [comment]
@smahdi 

سلام، moment باید قبل از moment-jalaaji بار گذاری شده باشه. 

https://momentjs.com/

**Comment by smahdi** [comment]
باید از ابتدا لود شود.

**Comment by sIiiS** [comment]
برای من هم همین ارور را از ورژن 2.17.1 به بعد میده ... جلالی بعد از مومنت اصلی لود میشه و اگر ورژن رو مثلا به 2.8.1 عوض کنم، درست میشه
