### ISSUE TITLE
create a demo page?

### ISSUE THREAD

**Issue by mortezakarimi64** [jalaali/moment-jalaali#88]
Hi.
Please provide a demo page for your project?
Thank you

**Comment by alitaheri** [comment]
@mortezakarimi64 What extra information would a demo page for an extension library provide? moment js has a big website for it that somehow documents pretty much anything you can do with this one. And there really isn't anything visual we can represent.

But if you have creative ideas that could help people learn the code faster. A PR is always welcome 👍 👍
