### ISSUE TITLE
نمایش اعداد به صورت انگلیسی

### ISSUE THREAD

**Issue by monala** [jalaali/moment-jalaali#89]
ایا فونت وزیر اعد را هم به صورت فارسی نمایش می دهد؟ اعدادی مثل تاریخ را لاتین نمایش میدهد.
<img width="204" alt="screen shot 2017-04-17 at 1 58 50 am" src="https://cloud.githubusercontent.com/assets/16857813/25074634/4a3af410-2315-11e7-9fed-1aa915e77af4.png">

**Comment by alitaheri** [comment]
<div dir="rtl">
برای نمایش اعداد بصورت فارسی ۲ راه وجود دارد:

 

۱. فونتی‌ که اعداد ascii را فارسی نمایش دهد.

۲. تبدیل دستی‌ تمامی عدد به متناظر خود در طیف اعداد عربی‌ unicode
</div>

[Font Glyph Editing](https://www.technameh.com/%D8%B1%D8%A7%D9%87-%D8%AD%D9%84-%D8%A7%D8%B9%D8%AF%D8%A7%D8%AF-%D8%A7%D9%86%DA%AF%D9%84%DB%8C%D8%B3%DB%8C-%D9%88%D8%A8-%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C/)

[Unicode Character Shift](https://github.com/mohebifar/persian.js)
