### ISSUE TITLE
information: used your plugin to adapt persian version of daterangepicker

### ISSUE THREAD

**Issue by misamae** [jalaali/moment-jalaali#90]
Thank you for providing this component. I have used your component to adapt Persian version of daterangepicker component. You can find the component here https://github.com/misamae/persian-bootstrap-daterangepicker. 

This is a very experimental work and I intend to fix the bugs if there is interest.

**Comment by alitaheri** [comment]
Thanks for the reference. Feel free to add your project to related projects when it production ready 👍

**Comment by misamae** [comment]
Thank you for providing this component
