### ISSUE TITLE
Use localized numbers

### ISSUE THREAD

**Issue by sorousht** [jalaali/moment-jalaali#91]
Hi

If you set `moment.locale("fa");` and use `moment.loadPersian();`, You see this:
```javascript
m = moment('1360/5/26', 'jYYYY/jM/jD') // Parse a Jalaali date
m.format('jYYYY/jM/jD') // 1360/5/26
```
But I expect to see something like the below line, because I have configured moment to use **fa** locale.
```javascript
m.format('jYYYY/jM/jD') // ۱۳۶۰/۵/۲۶
```
I thin it would be great if we could consider the locale instaed of `moment.loadPersian();` ;-)

**Comment by behrang** [comment]
`loadPersian` is optional. If you don't need it, just don't use it. `locale('fa')` will be sufficient for your case.
