### ISSUE TITLE
Support Datetimepicker

### ISSUE THREAD

**Issue by bahmansh** [jalaali/moment-jalaali#92]
Hello
Im using [datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker) that it use moment.js
but when i use your moment-jalaali.js datepicker dont work.

can u modify your moment-jalaali to support it?

thanks.

**Comment by alitaheri** [comment]
This was discussed many times before. I once tried to make something similar work. But it's simply way too complex and error prone to achieve. You're welcome to try. But I would suggest you fork datetimepicker and modify that one to work with moment-jalaali ( as I did with [material-ui](http://www.material-ui.com/#/components/date-picker) ). I'm sure a lot of people would appreciate it if you did :grin:

**Comment by fingerpich** [comment]
I have made a [fork](https://github.com/fingerpich/jalali-moment) that I think it is solved this issue.

```js
moment.useJalaliSystemPrimarily();
moment().format('YYYY/MMMM/D'); // 1396/Khordaad/30
```
