### ISSUE TITLE
Invalid Date responded  at Specific Date

### ISSUE THREAD

**Issue by FaShapouri** [jalaali/moment-jalaali#93]
Dear Behrang;

I am using this lib for three months and I did not see this problem till know.

Converting date works fine but at specific date it returns Invalid date; I am using this code at api, here is my code:

```
var moment = require('moment');
var momentJalali = require('moment-jalaali');

  .post(function (req, res) {

    var jFormat = "jYYYY-jM-jD HH:mm:ss z";
    var format = "YYYY-M-D HH:mm:ss z";
    console.log("pure : " + req.body.date);

    var date = moment(req.body.date).tz('UTC').format(format);
    console.log("moment : " + date);


    date = momentJalali(date.toString(), jFormat).format(format);

    console.log("momentJalali : " + date");
}
```

> Output:

```
pure : 1396-02-30T00:00:00.00+04:30
moment : Invalid date
momentJalali : Invalid date

pure : 1396-02-29T00:00:00.00+04:30
moment : 1396-2-28 19:30:00 UTC
momentJalali : 2017-5-18 19:30:00 
```

The problem is 30th Ordibehesht (the second month)

I know the moment is returning Invalid date and the issue is on that library but because of my input in Jalali format I prefer to ask it here  and hope you can find the solution.

**Comment by FaShapouri** [comment]
Oh my god, I made a big mistake; I am trying to convert a date to February month which has maximum 29 days!

The Invalid result is my fault; I need to convert date to Gregorian then apply time zone, but I don't know how can I do that.

**Comment by FaShapouri** [comment]
I use this code to fix my problem:

`    var date = momentJalali(req.body.date, jFormat).tz('UTC').format(format);
`

**Comment by behrang** [comment]
Ok, seems to me that everything is fine. Can we close this?
