### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by alitaheri** [jalaali/moment-jalaali#95]
@behrang I think It's time for another release. The last PR that a lot of people have been asking for should be released.

**Comment by behrang** [comment]
Yes, of course. I forgot to add you to NPM publishers. You are now the other owner of `moment-jalaali`. 

Also please remember to publish bower and component versions too.

You might also want to release 1.0.

**Comment by alitaheri** [comment]
@behrang Thank you.

There is one problem though. I have no experience with bower and component, but from what I understand a simple tag would take care of them. Should I do something extra?

P.S. Should we consider dropping support? they both are deprecated. and have been for too long.

**Comment by behrang** [comment]
Ok, drop support for both of them.
