### ISSUE TITLE
bower.json missed

### ISSUE THREAD

**Issue by sajjad-shirazy** [jalaali/moment-jalaali#98]
could you please return it back

**Comment by alitaheri** [comment]
`bower` is deprecated 😅 😅 Sorry, we're dropping support for it.

**Comment by sajjad-shirazy** [comment]
دوست عزیز

نمی شه که تو پروژه های بزرگ به محض اینکه یه بخشی دیپریکیت شد کل ساختار رو تغییر داد.
دلیلی نداره شما ساپورت نکنید. ضمن اینکه توی خود سایت نوشته ما هنوز مینتین می کنیم.

**Comment by alitaheri** [comment]
@sajjad-shirazy You're welcome to bring it back. I don't know much about bower. But if you can bring the file back and update it as necessary. We'll gladly accept 👍
