### ISSUE TITLE
improving the `moment-jalaali` typings

### ISSUE THREAD

**Issue by VahidN** [jalaali/moment-jalaali#99]
[the current typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/moment-jalaali/index.d.ts#L16) of this library doesn't accept any arguments for the `loadPersian` method:
```typescript
function loadPersian(): void;
```
But [its original](https://github.com/jalaali/moment-jalaali/blob/master/build/moment-jalaali.js#L1090) version does.
So it can be changed and improved to: 
```typescript
function loadPersian(args?: any): void;
```

**Comment by alitaheri** [comment]
@VahidN The typings aren't kept here. I'll fix the typings when I get the chance ( or you can do it yourself ). Please open typings related issues here: https://github.com/DefinitelyTyped/DefinitelyTyped
